### ISSUE TITLE
Define API Types for stake pool metadata

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#1063]
# Context

Part of [WB-25 Collect stake pool metadata](https://jira.iohk.io/projects/WB/issues/WB-25).

The API client must be able to view metadata (when available) of the available stake pools.

# Decision

1. Modify `swagger.yaml` to include metadata within the `GET /stake-pools` (list) endpoint.

Metadata looks like this. (Note lack of pool ID)
```json
{
  "title": "Stake-pool Metadata",
  "type": "object",
  "required": [
    "ticker",
    "homepage",
    "pledge_address"
  ],
  "additionalProperties": false,
  "properties": {
    "ticker": {
      "type": "string",
      "minLength": 3,
      "maxLength": 4
    },
    "homepage": {
      "type": "string",
      "format": "uri"
    },
    "pledge_address": {
      "type": "string",
      "format": "bech32"
    }
  }
}
```

Add this `metadata` as a nullable attribute of the stake pool json type.

2. Define a corresponding `StakePoolMetadata`.

```haskell
data StakePoolMetadata = StakePoolMetadata
    { ticker :: Text -- or a newtype if you wish
    , homepage :: Network.URI.URI
    , pledgeAddress :: Text -- This is an _encoded_ bech32 address
    }
```

3. Instances.
 - The `FromJSON` instance will parse the homepage URI and (defensively) bomb out if the scheme is not http(s) (even though the data is validation, we never want to pass dodgy links to Daedalus). Leave the address as encoded bech32 - no need to decode it.
 - `ToJSON` should be pretty simple. See [`registry.hs`](https://github.com/input-output-hk/testnet-stake-pool-registry-validator/blob/master/app/registry.hs) for more info.

4. Add a `Maybe (ApiT StakePoolMetadata)` to `ApiStakePool`.

# Acceptance Criteria

1. The API types and schemas for listing stake pools must support optional metadata about each pool.

---

# Development 

- As above.
- I have decided to drop use of the `URI` type and `Network.URI.parseURI` because the registry is already validated.

# QA 

- There is a golden test in `lib/core/test/unit/Cardano/Wallet/Api/TypesSpec.hs` to maintain the `StakePoolMetadata` JSON structure.
- There is another test in that module for handling an invalid ticker ID.

**Comment by jonathanknowles** [comment]
@rvl Just a minor thing: I'm guessing that the convention in the swagger specification is that properties are named in `camelCase` style, so perhaps:

`pledge_address` -> `pledgeAddress`

**Comment by KtorZ** [comment]
@jonathanknowles actually no, we use `snake_case` for fields. Though, I just noticed that most path parameters are in `camelCase` (though it doesn't really have any impact here..). Consistency would be best and `snake_case` is definitely the one to pick :) 

(why: a) because that's what already used by the API, changing to camel would be a breaking change, b) snake_case was a conscious choice in the API design as it is arguably more readable than camelCase).

**Comment by jonathanknowles** [comment]
> @jonathanknowles actually no, we use `snake_case` for fields.

Ah sorry, you're right. My apologies for the noise. (I was looking at the wrong thing.)

**Comment by KtorZ** [comment]
(I agree though it's confusing that we use camelCase for path parameters :/ )

**Comment by piotr-iohk** [comment]
lgtm -> additional test #1070.

**Comment by KtorZ** [comment]
@piotr-iohk I saw your message on Slack (about enforcing stricter validation on the data received) but answering here to keep some traceability. 

a) I'd suggest not to _yet_ at least. There are some last minute problems raised regarding the registry and the format of some data may change in the upcoming days. This shouldn't prevent the progress of this story though because the overall idea would stay the same but we will have to tweak a bit the JSON fields and their format. So, let's wait for things to stabilize first.

b) If we enforce a TLS connection for reaching the registry server, we can (and should) make sure that we are dealing with the right server behind the connection by checking the server TLS certificates.

**Comment by piotr-iohk** [comment]
Closing.
