### ISSUE TITLE
Add `Wallet.estimateJoinStakePoolFee`

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1094]
# Context

We currently have [`selectCoinsForPayment`](https://github.com/input-output-hk/cardano-wallet/blob/870914d3e684191bf5953f6445b0f1dbf32601d2/lib/core/src/Cardano/Wallet.hs#L738-L771), [`estimatePaymentFee`](https://github.com/input-output-hk/cardano-wallet/blob/870914d3e684191bf5953f6445b0f1dbf32601d2/lib/core/src/Cardano/Wallet.hs#L829-L851) and [`selectCoinsForDelegation`](https://github.com/input-output-hk/cardano-wallet/blob/870914d3e684191bf5953f6445b0f1dbf32601d2/lib/core/src/Cardano/Wallet.hs#L773-L799).

We can estimate the fees of a normal transaction before submitting it. With WB-32 we want to estimate the fees for joining a stake-pool.

These functions do not appear to have direct unit tests.

# Decision

Add a `Wallet.estimateJoinStakePoolFee` function to complete the pattern of the three mentioned functions.

# Acceptance Criteria

1. There _must_ exist a function in `Cardano.Wallet` that can estimate the fees required to join a stake-pool

# Development 

- I have a feeling there _might_ be opportunities for refactoring here
- #1116 

# QA 

- Added integration test scenarios here: https://github.com/input-output-hk/cardano-wallet/blob/decdad3e649ae9278d47815926d729ee56e25941/lib/jormungandr/test/integration/Test/Integration/Jormungandr/Scenario/API/StakePools.hs#L515-L558

**Comment by jonathanknowles** [comment]
@Anviking, are you able to expand a little more on the following point:

> If opportunity arises, we may refactor the functions.

 I suspect this is something that could go in the `Development` section (instead of being an acceptance criterion per se). What do you think?

**Comment by jonathanknowles** [comment]
**Regarding the precision of our fee estimation:**

When we added support for migration from Byron wallets (to Jörmungandr wallets), we were able to offer a **_precise_** fee calculation endpoint (`getByronWalletMigrationInfo`). Furthermore, we actually _test_ that the predicted value is precisely the same as the eventual value in our integration tests. (See `BYRON_MIGRATE_03`.)

The reason we can do this is because the wallet UTxO is a value of type `Map`, and converting any given `Map k v` to a list with the `toList` operation always produces a list of `[(k, v)]` in a _deterministic order_. (It turns out to be ascending order, but this would work just as well with some other deterministic order.) This order is _only_ dependent on the contents of the map, and _independent_ of the order in which the map was originally constructed. (The order in which the UTxO is deserialized from the database is irrelevant.)

So given that both the `estimateJoinStakePoolFee` endpoint and `joinStakePool` both use the same coin selection algorithm, if the UTxO hasn't changed between calling the `estimateJoinStakePoolFee` function and `joinStakePool` function, then both ought to produce an identical coin selection, which is equivalent to an identical fee.

Of course, if we elect to perform _randomization_ of the UTxO order in our coin selection algorithm, then the above point won't hold.

**Comment by jonathanknowles** [comment]
**Regarding the calculation of the fee:**

If I'm not mistaken, the fee for a normal transaction seems to be calculated with a composition of the following functions:

1. `estimateSize :: CoinSelection -> Quantity "byte" Int`
2. `computeFee :: FeePolicy -> Quantity "byte" Int -> Fee`

However, there is also a `computeCertFee` function in `Wallet.Primitive.Fee` that we might need to take into account. It's an additional fee on top of the normal transaction fee above.

**Comment by KtorZ** [comment]
> If the UTxO hasn't changed between calling the estimateJoinStakePoolFee function and joinStakePool function, then both ought to produce an identical coin selection

This statement is actually false :upside_down_face: UTxO are selected randomly to cover for fee. That selection may vary from a request to another. Therefore, even for an unchanged UTxO, several calls might result in different selections and different fees.

The case for the Byron migration is very special because, there are no randomness going on: we try to migrate everything.
