### ISSUE TITLE
Create new Address

### ISSUE THREAD

**Issue by Sotatek-CongNguyen** [cardano-foundation/cardano-wallet#1107]
# Context

I couldn't find API to create a new address. I found a concerned API is "get list addresses". I could pass a param that is "used" or "unused". But I don't know the amount of address I can get is limited or unlimited and addresses returned are different from past addresses returned. I want to change the state of address I got into "used".

# Decision

I want to execute one basic task: create a or some new addresses.

# Acceptance Criteria

Creating some new addresses that have not used.

**Comment by rvl** [comment]
Hi @Sotatek-CongNguyen

There number of addresses is unlimited, however [list addresses](https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/listAddresses) will only display the next 20 unused addresses.

This number is the "address pool gap", a parameter supplied when [creating/restoring a wallet](https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/postWallet).

However, note that once an address is used (i.e. a payment has been made to that address), a new address will be automatically generated, so that there are always 20 unused addresses available.

Hope this helps.

**Comment by Sotatek-CongNguyen** [comment]
Tks @rvl,
But I think that it's more convenient if we have an API creating the address really new!

**Comment by KtorZ** [comment]
@Sotatek-CongNguyen unfortunately, things are not that simple. Cardano wallets implement a variation of [BIP-0044](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki) where the number of consecutive unused addresses has to be monitored closely. This is to allow wallets to be restored within a rather acceptable bound and, to be shared across various softwares (e.g. Daedalus <-> Yoroi). 

The API doesn't allow you to violate this rule because it would make your wallet useless among the ecosystem.
