### ISSUE TITLE
Encountered some issues during Cardano wallet onboarding

### ISSUE THREAD

**Issue by kristieguo** [cardano-foundation/cardano-wallet#1167]
Hi there. 

This is the team of Jadepool Custody, a leading cryptocurrency custody product based in Shanghai. This is our website: https://www.jadepool.io/. So far we have supported 26 blockchains. Right now we are in the process of supporting Cardano. 

Our developer has encountered some issues and is having some questions during onboarding. I was wondering if you can provide some technical help through a platform that we can get responses as soon as possible. Maybe creating an exclusive Slack chat room for us. 

Thank you,
Jadepool Team

**Comment by KtorZ** [comment]
Hi @kristieguo. For lack of a better place at the moment, I'd suggest to have this discussion here, provided that your questions are about the wallet (if they are not, I will happily redirect you to the relevant projects in the Cardano eco-system :))

**Comment by kristieguo** [comment]
@KtorZ Hi, here is the list of questions we have. If they are not relevant to this project, please redirect me. Thank you.

1.1. Where to find the project of Cardano node? And RPC API?
1.2. Are there multiple testnet for Cardano? Which to choose? How to configure for node?

2.1. How to use API to get details of certain block by block index or block hash?
2.2. How to use API get balance of an address?
2.3. How to use API to look up a transaction by hash?
2.4. How to use API to broadcast a transaction?

3.1. I see on Github the SDK project says the work is still in progress and not suitable for production. Is there any SDK ready for use on production?
3.2. If there is, does it have method for generating address for both mainnet and testnet?
3.3 Are Addresses generic in different testnet？In what way should we generate address for mainnet and testnet?
3.4. Is there any method in SDK to sign transaction?

**Comment by KtorZ** [comment]
**1.1. Where to find the project of Cardano node? And RPC API?**

- The component for the Shelley MainNet can be found on https://github.com/input-output-hk/cardano-node/
  Note however that the node API is a in-house solution which at the moment, requires using a Haskell client / node. Likely, you'd be looking to deal with services built on top of the node like `cardano-wallet` or `cardano-explorer`.

- The component for the Shelley TestNet can be found on https://github.com/input-output-hk/jormungandr.
   Documentation is available on the README. 

**1.2. Are there multiple testnet for Cardano? Which to choose? How to configure for node?**

There are multiple networks available for testnet indeed at the moment. Depending on the nature of your activity, you may want to favor one instead of the other. After the deployment for the second phase of the incentivized testnet, we'll likely keep only two testnets: nightly (with edge builds for early testing) and the official testnet. Genesis parameters and configuration for joining the testnets are available here: https://hydra.iohk.io/build/1485111/download/1/index.html

**2.1. How to use API to get details of certain block by block index or block hash?**
**2.2. How to use API get balance of an address?**
**2.3. How to use API to look up a transaction by hash?**
**2.4. How to use API to broadcast a transaction?**
All these questions can be answered by an **explorer**. For the incentivized testnet, you have two options (REST or GraphQL) detailed here: https://input-output-hk.github.io/jormungandr/quickstart/04_explorer.html.

**3.1. I see on Github the SDK project says the work is still in progress and not suitable for production. Is there any SDK ready for use on production?**
Are you referring to https://github.com/input-output-hk/cardano-js-sdk ? If yes then indeed, this SDK isn't ready for production use. There are currently no SDK available for the MainNet. For the ongoing TestNet however, you may rely on https://github.com/input-output-hk/js-chain-libs. 

**3.2. If there is, does it have method for generating address for both mainnet and testnet?**
The address format for the MainNet is still going under some design changes. For the TestNet, you may rely on: https://input-output-hk.github.io/jormungandr/jcli/address.html. Addresses generated in the TestNet won't be compatible with the MainNet.

**3.3 Are Addresses generic in different testnet？In what way should we generate address for mainnet and testnet?**
Cf previous question.

**3.4. Is there any method in SDK to sign transaction?**
See the `TxBuilder` from js-chain-libs.

**Comment by kristieguo** [comment]
@KtorZ Hi thank you for your response. We still have some following questions regarding your answers.

1. your answer: "The component for the Shelley MainNet can be found on https://github.com/input-output-hk/cardano-node/
Note however that the node API is a in-house solution which at the moment, requires using a Haskell client / node. Likely, you'd be looking to deal with services built on top of the node like cardano-wallet or cardano-explorer.
The component for the Shelley TestNet can be found on https://github.com/input-output-hk/jormungandr.
Documentation is available on the README."

question: This API is v0 API, is it suitable for use on production? We found a v1 API and not sure if we could use it: https://cardanodocs.com/technical/wallet/api/v1/?v=1.6.0. 

2. We try to use  /api/v0/block/{block_id} to get block details but no valid JSON returned.

3. Your answer: "All these questions can be answered by an explorer. For the incentivized testnet, you have two options (REST or GraphQL) detailed here: https://input-output-hk.github.io/jormungandr/quickstart/04_explorer.html."

question: GraphQL seemed doesn't work. Do you have documentation for query parameters?  http://127.0.0.1:8443/explorer/graphql
curl \
    -X POST \
    -H "Content-Type: application/json" \
    --data '{'\
        '"query": "{'\
        '   status {'\
        '       latestBlock {'\
        '           chainLength'\
        '           id'\
        '           previousBlock {'\
        '               id'\
        '           }'\
        '       }'\
        '   }'\
        '}"'\
    '}' \

4. Your answer: "Are you referring to https://github.com/input-output-hk/cardano-js-sdk ? If yes then indeed, this SDK isn't ready for production use. There are currently no SDK available for the MainNet. For the ongoing TestNet however, you may rely on https://github.com/input-output-hk/js-chain-libs."

question: We want to go on production after testing. What should we use then?

5. Your answer: "The address format for the MainNet is still going under some design changes. For the TestNet, you may rely on: https://input-output-hk.github.io/jormungandr/jcli/address.html. Addresses generated in the TestNet won't be compatible with the MainNet."

question: How does exchanges that already supported Cardano generate mainnet addresses? We hope we can put Cardano on production soon.

**Comment by kristieguo** [comment]
@KtorZ Hi, we'd really appreciate it if you could answer our questions as soon as possible. Thank you.

**Comment by KtorZ** [comment]
Hi @kristieguo we are a bit busy on the development side at the moment ^.^ 
I am trying to find someone to help with your questions. Please be patient :pray:

**Comment by KtorZ** [comment]
Closing this. I believe you guys received an email from Neville to continue the discussion :wave:

**Comment by kristieguo** [comment]
@KtorZ No we didn't receive any email. The email address is contact@jadepool.io
