### ISSUE TITLE
Partial missing pool metadata

### ISSUE THREAD

**Issue by gufmar** [cardano-foundation/cardano-wallet#1180]
---
name: Bug report
about: Create a bug report

---

# Context
 
By querying cardano-wallet-jormungandr endpoint v2/stake-pools (current master head) all on-chain registered pools are visible.

Most of them show up also with metadata from CF stakepool registry. But not all.

For example these pool-ID miss the metadata.

```
4cf8844b129f2984ae5a52ac6bf5657c007b33e0de2a2989955c4bb54b11e0f3

366988faf204e98d3cafc4f0656257bca76a93ed6db298e92111aee0c9d00365

2ea368d8e490b4202f152556362d1eaaa19b57b0665a341844a0c0f2f9985616
```

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | 2019.12.13 (git revision: f3576be15de4976e753dea212aa5d44c334bd204) |
| Platform     | Linux          |
| Installation | compiled from source  |

# Steps to Reproduce

 `curl http://localhost:8082/v2/stake-pools`

## Expected behavior

Show metadata for all pools who have CF stakeool registrations.
Or explain what's wrong with metadata or on-chain registration

## Actual behavior

 ```
   { 
      "metrics":{ 
         "controlled_stake":{ 
            "quantity":0,
            "unit":"lovelace"
         },
         "produced_blocks":{ 
            "quantity":0,
            "unit":"block"
         }
      },
      "cost":{ 
         "quantity":0,
         "unit":"lovelace"
      },
      "margin":{ 
         "quantity":7,
         "unit":"percent"
      },
      "apparent_performance":0,
      "id":"366988faf204e98d3cafc4f0656257bca76a93ed6db298e92111aee0c9d00365"
   },```

---

**Comment by KtorZ** [comment]
@gufmar May I ask you to follow the [template for filling bugs](https://github.com/input-output-hk/cardano-wallet/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) please :pray: 
In particular, what versions are you using? 

Also, note that the metadata are cached locally and only renewed every hour.

**Comment by gufmar** [comment]
@KtorZ ok updated the issue based on bug template

metadata for pool ID 366988...  was the first PR and merge. So it's not caching.

**Comment by KtorZ** [comment]
Okay, this is an expected behavior on `f3576be15`. This release heavily relies on [get stake distribution](https://input-output-hk.github.io/jormungandr/jcli/rest.html#get-stake-distribution) from Jörmungandr REST API which only show pools that are _active_ (i.e. that have registered the epoch before the previous epoch). 

So, the missing pools should show up as expected 2 epochs after their registration. 

If you like to live ~~dangerously~~ on the edge, you could also use the latest build from the current master ([windows](https://hydra.iohk.io/build/1498627), [mac os](https://hydra.iohk.io/build/1498616) or [linux](https://hydra.iohk.io/build/1498606)) which now resolves the list based on the actual registration found by following the chain taking into account newcomers earlier.

**Comment by gufmar** [comment]
That seems not possible to me. In current epoch 0 (and 1) only IOHK pools have an active stake.

But v2/stake-pools endpoint currently return 68 stakepool datasets.
https://gist.github.com/gufmar/cdbbe68918ec38a2cd462a7e5594870e

All IOHK pools also don't contain metadata. I guess because they are not registered (yet) in CF stakepool registry? So this is expected behaviour.

But "partial missing pool metadata" seems a bit strange to me.

**Comment by gufmar** [comment]
hold on ... might found a cause ...

**Comment by KtorZ** [comment]
@gufmar Sorry, I read your issue a bit too quickly initially :thinking: 

Okay, let's investigate why `366988faf204e98d3cafc4f0656257bca76a93ed6db298e92111aee0c9d00365` doesn't have metadata.

**Comment by KtorZ** [comment]
This pools is associated with the following owner on nightly:

```
ed25519_pk129p03fxu9wc8dg5qhetttf4anqnp5j05s8vltcjzafq2zkqmf2rqznw4u6
```

And, there's no metadata associated with this owner in the registry:

![Screenshot from 2019-12-14 19-57-25](https://user-images.githubusercontent.com/5680256/70853275-05477a00-1eac-11ea-929f-249709e23c34.png)


So, there's no metadata attached to this pool.

**Comment by KtorZ** [comment]
So to clarify, if your question is 

"Why do some stake pools returned by the API don't have metadata?"

The answer is: because only owners who are registered on the CF can be associated with their stake pools. So, some pools may have been registered on-chain, but their owners don't have submitted anything to the registry. (This is seemingly hinted by the [API documentation](https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/listStakePools) in the response of the "listStakePools" endpoint, the `metadata` field is the only one that isn't "required". So it may or may not be present in each resource).

There's also the special case of pools with multiple owners. In this scenario, at least one owner should have submitted metadata and if several have published metadata, they should all be identical (modulo the public key) or, all metadata regarding this pools will be discarded altogether.
