### ISSUE TITLE
API data filtration and pagination

### ISSUE THREAD

**Issue by Fell-x27** [cardano-foundation/cardano-wallet#1216]
# Context

the REST API list-endpoints needs for filters.

# Decision

For the cardano-sl version of wallet there were filters and pagers as a part of a REST API.
So you can choose how much data you need, how it should be selected and sorted.

Right now there are no any ways to do something like that(except transaction list time-range querying). For example, /v2/stake-pools is returning about 500+ items, and spends about 2 seconds for it. 

This is not scalable solution with linear perfomance degradation.

# Acceptance Criteria

1. The API _must_ support filtration and pagination of lists returned by endpoints.
2. There should be optional parameters for query for this purpose.

---

# Development 

# QA

**Comment by KtorZ** [comment]
Hi :) 
Thanks for reaching out. We are currently analyzing the need for pagination on various endpoint. In most cases however, it is rather reasonable to de-prioritize it over more important features.  

Incidentally, we are already measuring database query times as well as API response latency delays on nightly builds (see https://buildkite.com/input-output-hk/cardano-wallet-nightly/builds/329). 

As for the list stake pools endpoint, it is a bit singular and pagination wouldn't do any help here. This endpoint has to resolve data from 3 data-sources and make sure they are in sync altogether. One of source being a github repository :upside_down_face:  ... the metadata from the registry are cached however in order to remove the main bottleneck in the call. Still, we haven't yet spent much time looking for any other optimizations in this area. I agree that ~1s with caching still is a long time. But, there are ways to approach the problem before introducing pagination. 

```
09:06:21 $ time cardano-wallet stake-pools list
real	0m2,665s
user	0m0,105s
sys	0m0,030s

09:06:24 $ time cardano-wallet stake-pools list
real	0m1,157s
user	0m0,141s
sys	0m0,012s
```

Having said that, note that we keep track of user stories and feature backlog in a different issue tracker (on JIRA). Pagination is already part of our backlog; I'll therefore close this issue, but, point heard :)
