### ISSUE TITLE
Error in the log after deleting a wallet

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#1242]
# Context
 
 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | 2019.12.23 (git revision: 7e7c9111c98330c560de7a2a99fd93ef19ebe228) |
| Platform     | Linux (probably all)         |
| Installation | From source            |

# Steps to Reproduce

**Note**: it is observed for all types of wallets: shelley and all byron (random, yoroi, trezor, ledger)

1. Start wallet
```
cd lib/jormungandr/test/data/jormungandr/test_scripts/
cardano-wallet-jormungandr launch --genesis-block ../block0.bin --node-port 8080 --state-dir ./data_launch -- --secret ../secret.yaml --config ../config.yaml
```
2. create a wallet `cardano-wallet-jormungandr wallet create`
3. delete a wallet `cardano-wallet-jormungandr wallet delete <wallet id>`

## Expected behavior

Wallet is deleted. There is no error in the log.

## Actual behavior
 
Wallet is deleted. In the log there is an error:
```
[cardano-wallet.worker:Error:237] [2020-01-02 10:34:35.47 UTC] 14598538: Worker has exited unexpectedly: SQLite3 returned ErrorMisuse while attempting to perform close: bad parameter or other API misuse

```

---

# Resolution 

---

# QA

**Comment by jonathanknowles** [comment]
I managed to confirm this error with running with commit `c7d9bc481fd9cebe8dfe25e3f7d9842158ec3f06`.

**Comment by jonathanknowles** [comment]
Okay. I think I've managed to locate the root cause of this issue. It appears that in the course of the API call, `destroyDBLayer` is called **twice**:

```hs
[cardano-wallet.api:Info:255] [2020-01-07 05:02:04.59 UTC] [RequestId 1] [DELETE] /v2/wallets/67f6430300c403a0a0f2920c2a7c4cd565118a9d
[cardano-wallet.database:Debug:255] [2020-01-07 05:02:04.59 UTC] Closing database (/home/jsk/.local/share/cardano-wallet/jormungandr/testnet/wallets/seq.67f6430300c403a0a0f2920c2a7c4cd565118a9d.sqlite)
[cardano-wallet.database:Debug:185] [2020-01-07 05:02:04.63 UTC] Closing database (/home/jsk/.local/share/cardano-wallet/jormungandr/testnet/wallets/seq.67f6430300c403a0a0f2920c2a7c4cd565118a9d.sqlite)
[cardano-wallet.worker:Error:185] [2020-01-07 05:02:04.63 UTC] 67f64303: Worker has exited unexpectedly: SQLite3 returned ErrorMisuse while attempting to perform close: bad parameter or other API misuse
[cardano-wallet.api:Info:255] [2020-01-07 05:02:04.63 UTC] [RequestId 1] 204 No Content in 0.043179776s
[cardano-wallet.api:Debug:255] [2020-01-07 05:02:04.63 UTC] [RequestId 1] Completed response to API request
```
The second call to `destroyDBLayer` results in an `ErrorMisuse` failure, as we're attempting to close a DB connection that's already closed.

Within the API server implementation of `deleteWallet`, there are two places that indirectly call `destroyDBLayer`:
1.  `liftIO $ (df ^. #removeDatabase) wid`
2. `liftIO $ Registry.remove re wid`

So we need to adjust the implementation of `deleteWallet` so that `destroyDBLayer` is only called once.

**Comment by KtorZ** [comment]
@jonathanknowles note that, the `deleteWallet` handler was recently "touched" in order to fix another issue: database files were not properly removed upon deletion (especially on Windows). The tricky part with that function is that we have two concurrent calls that kinda need to be executed in a transaction manner. 

1. We need to close and remove the database file.
2. We need to remove the database from the registry. 

If we do 2. first and something goes wrong with 1., then we have "removed" the worker, but we now have a database file that is still there. So, the wallet isn't usable but will re-appear on restart. Yet, when something went wrong on users' machine, it typically caused the database file to become corrupted and therefore, not usable even after a restart. 

If we do 1. first, then we are sure that at least, the database is removed and, the worker will eventually die. Now, "Registry.remove" is causing issue mainly because it also kills the underlying worker thread:

```hs
    alterF = \case
        Nothing -> pure Nothing
        Just wrk -> do
            -- NOTE: It is safe to kill a thread that is already dead.
            killThread (workerThread wrk)
            return Nothing
```

Few options here that I see:

1. Have `remove` take an extra "cleanup" argument, an action that gets run after `killThread`, regardless of whether `killThread` raised an exception or not (i.e. using something like `finally`). That action being "removeDatabase". 

2. Make `remove` returns the worker thread instead of killing it, and live the killing logic within the delete handler. 

3. Make "destroyDBLayer"  a bit more lenient and allow destroying an already destroyed database.

**Comment by jonathanknowles** [comment]
Hi @piotr-iohk!

With the merging of PR #1248, it seems that this issue has been addressed. Should I go ahead and close it?

**Comment by piotr-iohk** [comment]
@jonathanknowles thanks! Closing, issue no longer observed. (When done please just move into QA column in https://github.com/input-output-hk/cardano-wallet/projects :) )
