### ISSUE TITLE
Cannot list wallets when using same state directory but different genesis

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#1292]
# Context

https://github.com/input-output-hk/cardano-wallet/issues/1281#issuecomment-576636085

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | 2020.1.14 (git revision: 5e690157e636532fa27de88622aad8f85b7919e5) |
| Platform     | Linux (all?)        |
| Installation | From source code            |

# Steps to Reproduce

 - Create a standalone private blockchain (e.g. using the integration config).
 - Turn on the wallet server and wait for a few slots / epochs.
 - **Create a wallet**
 - Turn the wallet off.
 - Change a setting in the genesis configuration and re-generate the genesis block (effectively creating another blockchain).
 - Restart the server on the same state directory.

In the log there is:
```
[cardano-wallet.wallet-engine:Error:29] [2020-01-21 11:04:31.30 UTC] Worker has exited unexpectedly: ErrCheckIntegrityDifferentGenesis (Hash {getHash = "\216\163\131S\189W\b]\213+\139U\169Ue\205W\215\158\SI\131}\151ed\ACK\250\186O~\233\&7"}) (Hash {getHash = "<\a\ETX\SO6\191\255\230~..\192\158R\147\211\132c|\210\240\EOT5n\243 \243\254lR\EOT\SUB"})
```
and then:

## Expected behavior

```
$ cardano-wallet-jormungandr wallet list
Ok.
[]
```

## Actual behavior
 
```
$ cardano-wallet-jormungandr wallet list
Something went wrong
```

---

# Resolution 

---

# QA

**Comment by jonathanknowles** [comment]
Confirmed on `v2020-01-21` (d188a5fcf73d26f51391c5aea5030dc8e152741d).

**Comment by KtorZ** [comment]
@jonathanknowles I did some investigation yesterday. The main issue is due to the worker not being unregistered from the registry when it dies.

**Comment by jonathanknowles** [comment]
@KtorZ wrote:
> @jonathanknowles I did some investigation yesterday. The main issue is due to the worker not being unregistered from the registry when it dies.

Yes, I found the same thing in my investigation.

But there's something else that's going on. The current implementation of `newWorker` returns a `Worker` **even if** evaluating the `before` action fails:

https://github.com/input-output-hk/cardano-wallet/blob/d188a5fcf73d26f51391c5aea5030dc8e152741d/lib/core/src/Cardano/Wallet/Registry.hs#L216-L220

Though the comment of the function explains that `newWorker` should return `Nothing` if the worker terminates unexpectedly before entering its `main` action.

One possibility here would be to change this function so that if `before` fails, we don't return a `Worker` from `newWorker`.

Thoughts?

**Comment by jonathanknowles** [comment]
> The main issue is due to the worker not being unregistered from the registry when it dies.

Just for the record: we discussed this in our team meeting and agreed to adjust the worker life cycle so that `newWorker` will handle the registration, requiring the caller to pass the registry as an argument. On cleanup (when the thread dies), this function will also handle unregistration from the registry map, preventing the situation where we can perform a successful lookup on a worker whose thread has already died.

**Comment by jonathanknowles** [comment]
We should investigate what would happen if a worker thread dies, w.r.t. Daedalus.

With PR #1301, if a worker thread dies, then its key is removed from the registry. In that case, the wallet will no longer be listed by `listWallets`, and the wallet will no longer be accessible to Daedalus.
