### ISSUE TITLE
Possible fee disrepancy on the sending tx via cardano-wallet-byron on testnet

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#1494]
# Context
 
Discrepancy observed when running tx on testnet which was unsuccessful. https://github.com/input-output-hk/cardano-wallet/issues/1462#issuecomment-603849720

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      |cardano-wallet `2020.3.16 (git revision: 73c3290b9a4ab173dd9fba54dea79c8cb55f93c3)`, cardano-node 1.8 and 1.9 |
| Platform     | Linux        |
| Installation | source            |

# Steps to Reproduce

 - Submit the same tx as in -> https://github.com/input-output-hk/cardano-wallet/issues/1462

## Expected behavior
Fee should match the formula https://cardanodocs.com/cardano/transaction-fees/

## Actual behavior
 
The tx is 359 bytes and according to [formula](https://cardanodocs.com/cardano/transaction-fees) calculated fee should be:

0.155381 + (0.000043946 × 359 bytes) = 0,171157614 ADA

The fee was:
171118 lovelace = 0,171118 ADA

---

# Resolution 

---

# QA

**Comment by KtorZ** [comment]
The fee calculation on Byron can't be perfect (and isn't) because we can't possibly know the size of change addresses upfront. The calculation is also quite complex due to the variable nature of CBOR encoded data structure (encoding the number "2" takes 1 byte, but encoding "26" takes 2 bytes). 

Therefore, one thing we have to make sure is that the wallet will always generate fees that are AT LEAST, covering for the minimum size of the transaction, and that are not _too large_. 

We do have a property that test exactly this! 

--> https://github.com/input-output-hk/cardano-wallet/blob/master/lib/byron/test/unit/Cardano/Wallet/Byron/TransactionSpec.hs#L231-L267

What this says is that, for any valid coin selection, and for any change address (Random, Icarus, Mainnet,Testnet..), the estimated transaction size (goal of the coin selection algorithms) is:

- At least equal to the actual size
- No bigger than the actual size + 12 bytes per change address.

So in practice, the fee might be slightly bigger, up to 527 lovelace per change address.

**Comment by KtorZ** [comment]
(Note, there was however mistakes in our estimator when this issue was reported, which were found by the property test above and fixed)
