### ISSUE TITLE
Missing funds / rare alternate wallet tx history

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1547]
# Context
 
 

On 2018-12-12 I lost 4 ada. I opened my cardano-sl wallet, and I believe generated an address before it was fully synced / on an old version, but I don't remember the details to well. I sent 4 ada to that address. I believe I installed a later Daedalus version, synced fully, but I never saw the 4 ada again.

That was — until 2020-04-01. When restoring my wallet in Daedalus FC1, the 4-ada address was there. No other funds were there. The tx history only included the 4-ada tx.

I deleted the state directory and tried again. Now, the balance was "as expected" (the 4-ada were missing like they used to be), and the balance matched what is reported by Yoroi-importer and cardano-sl Daedalus.

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | FC1 |
| Platform     | macOS          |
| Installation |  FC1 using official installer. cardano-sl Daedalus using official installer |

# Steps to Reproduce

Haven't found ways to reproduce.

## Expected behavior

- Wallet balance should be deterministic
- Addresses generated by cardano-sl and the new cardano-wallet should be recognised by the wallet

## Actual behavior
 

I somehow once used the legacy wallet to generate an address which
is not recognised by the legacy wallet
is not recognised by the new wallet…
…except for once (but not reproducible) where no other addresses were recognised

---

# Resolution 

---

# QA

**Comment by Anviking** [comment]
When manually trying to get the wallet to recognise the address in ghci, I traced the error to https://github.com/input-output-hk/cardano-wallet/blob/95a964bbca2ddffd948515d0cfabc9bfd701b0bd/lib/core/src/Cardano/Byron/Codec/Cbor.hs#L778.

**Comment by KtorZ** [comment]
Without clear reproduction path, it seems quite hard to pursue that one :/ ... Also, since these are quite old addresses it could actually be due to some changes in cardano-sl made a while ago (for example, a change to the nonce used for encrypted the payload); although the fact that this doesn't seem deterministic is pretty disturbing. 

It could also be that there's something else you missed and that would make it deterministic :thinking: ? 
What do you want to do with this ticket @Anviking ?
