### ISSUE TITLE
On Delete Cascade

### ISSUE THREAD

**Issue by kderme** [cardano-foundation/cardano-wallet#1551]
# Context
I recently added `On Delete Cascade` options to persistent quasiquoters https://github.com/yesodweb/persistent/pull/1056. I remember that was an issue when I worked at the wallet, long ago, and I think it may still be of interest.

# Decision

# Acceptance Criteria

---

# Development 

# QA

**Comment by kderme** [comment]
Related https://github.com/input-output-hk/persistent/commit/79f2ece07eafae005a703c8eda1bd2420b5e07b5

**Comment by KtorZ** [comment]
Awe, nice!

**Comment by KtorZ** [comment]
@kderme, we ran into a very unfortunate issue with the cascading deletion and the way persistent handles automatic migration though. Are you aware of this:

When new fields in a persistent model are found, persistent will, whenever possible attempts to automatically "migrate" the tables and it does so in basically 4 steps:

1. Create a _backup table of an existing table
2. Remove the original table with the extra / modified field
3. Re-create all rows from the backup table to the new 
4. Drop the _backup table

Now, the major issue with this and cascade deletions on foreign keys is that.. if any other table has a foreign reference with "ON CASCADE DELETE" to the table being updated, this other table gets completely emptied during the step2 :| ... 

Is it something your PR address by any chance? (from a quick glance, it doesn't seem like it and I guess this is more about fixing the internals of `persistent`).

**Comment by KtorZ** [comment]
(see also https://github.com/input-output-hk/cardano-wallet/issues/1279 )

**Comment by jonathanknowles** [comment]
@KtorZ wrote:
> Now, the major issue with this and cascade deletions on foreign keys is that.. if any other table has a foreign reference with "ON CASCADE DELETE" to the table being updated, this other table gets completely emptied during the step2 :| ...

Just to add some info which might be helpful to some:

In order to work around the issue of automatic migration deleting data from tables with foreign key constraints, we developed a workaround (in `cardano-wallet`) which disables foreign key constraints during automatic database migration: https://github.com/input-output-hk/cardano-wallet/pull/1340

**Comment by rvl** [comment]
We shouldn't use the automatic migrations generated by persistent. They aren't for production use.

**Comment by KtorZ** [comment]
Indeed, there's even a warning in persistent but it's really subtle. 

Looking back on this whole persistent integration, I think we shouldn't use persistent at all in the first place :/ ... The abstraction doesn't buy us much and actually add quite a fair level of complexity compared to plain SQL. Instead of plain SQL we now have a hybrid mix of plain SQL and persistent-specific edge cases. Great :no_mouth:

**Comment by rvl** [comment]
I agree the persistent query api is pretty hopeless unless you are doing really basic queries.

But persistent does provide us the with row <-> entity mapping functions which are useful, and the DDL isn't completely bad.

**Comment by KtorZ** [comment]
Yeah, although the mapping we get is pretty useless because we don't actually use the persistent types in the rest of the codebase, but we have other types. So we still require a manual mapping of our application type to the database types: https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/src/Cardano/Wallet/DB/Sqlite.hs#L669-L892

All these conversion functions completely defy the purpose of using persistent in the first place. Because we are now doing "Wallet <-> Persistent <-> SQL" instead of simply "Wallet <-> SQL"; and we even have to tell persistent how to convert to SQL half of those anyway:

https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/src/Cardano/Wallet/DB/Sqlite/Types.hs

I am not saying the DSL is bad, it's actually pretty good but it's really limited as soon as one wants to do something a bit more "clever" than simple CRUD requests. Persistent is great if one is looking for implementing a REST interface by directly wiring the API types to the database types. This is, I think, the main use-case that the persistent's developers had in mind and partly why we find these To/FromHttpApiData and To/FromJSON instances so close to the generated Persistent types.

**Comment by kderme** [comment]
Tbh I'm not familiar at all with the automatic migration provided by persistent, but I'm usually skeptical about similar stuff. They try to do something pretty complicated and general (over many different backends) and when the edge cases start to not work properly, you wonder the whole purpose of using them in the first place.

**Comment by KtorZ** [comment]
Closing this to clean up a bit the issue backlog. I've created a corresponding item in JIRA to track this.
