### ISSUE TITLE
Cardano Wallet & Cardano Node Communication

### ISSUE THREAD

**Issue by Mercurial** [cardano-foundation/cardano-wallet#1556]
# Context
I was wondering if there are any plans to make Cardano Wallet and Cardano Node communicate via TCP instead of IPC/Unix Sockets? I think there are good use cases where the node is running remotely and multiple wallets are connecting to the node via TCP from different machines. 

Is the decision of running it IPC only because of security concerns?

Thanks!

# Decision

# Acceptance Criteria

# Development 

# QA

**Comment by KtorZ** [comment]
Hey @Mercurial, I'll forward your question to the networking team who will be able to provide a better answer than I could on the subject.

**Comment by dcoutts** [comment]
Yes it is because of security.

The node does not trust remote peers at all, and that is reflected in the features available in the node-to-node protocol and paranoia about limits, timeouts etc.

But for the node-to-client case it provides a less paranoid protocol that is more convenient to use, doesn't have such defensive timeouts, and provides more functionality. For example the node-to-node protocol follows the usual security principles of not revealing information to attackers, so the transaction submission protocol does not even provide feedback on whether the transaction was accepted or rejected, whereas for local clients like wallets we provide detailed structured errors. Similarly, local clients are allowed to inspect the full ledger state and execute relatively expensive queries. Local clients can DoS the node, but that's ok because they run in the same security domain.

Now technically it's possible to bypass all this and use `systemd` socket activation to pass in a TCP socket for the node-to-client socket that the node uses. But if you do this then the responsibility is entirely on you to ensure only trusted clients can connect. You have been warned :warning:

**Comment by Mercurial** [comment]
> Yes it is because of security.
> 
> The node does not trust remote peers at all, and that is reflected in the features available in the node-to-node protocol and paranoia about limits, timeouts etc.
> 
> But for the node-to-client case it provides a less paranoid protocol that is more convenient to use, doesn't have such defensive timeouts, and provides more functionality. For example the node-to-node protocol follows the usual security principles of not revealing information to attackers, so the transaction submission protocol does not even provide feedback on whether the transaction was accepted or rejected, whereas for local clients like wallets we provide detailed structured errors. Similarly, local clients are allowed to inspect the full ledger state and execute relatively expensive queries. Local clients can DoS the node, but that's ok because they run in the same security domain.
> 
> Now technically it's possible to bypass all this and use `systemd` socket activation to pass in a TCP socket for the node-to-client socket that the node uses. But if you do this then the responsibility is entirely on you to ensure only trusted clients can connect. You have been warned ⚠️

I really appreciate the response and this makes alot of sense as-well, thank you very much!

> You have been warned ⚠️ 

I mean hey if dcoutts himself has warned me then I should really think this through haha!

have a good day and keep up the good work guys!

<3 IOHK & Cardano

**Comment by daoleno** [comment]
## Getting nodes and wallets to communicate

Install `socat` on each of the two machines 

```sh
apt install socat
```

Proxy Unix sockets on the node machine using TCP 

```sh
# Get the ipc configuration directory
SOCKET_DIR=`docker volume ls | grep node-ipc | xargs -n2 sh -c 'docker volume inspect $1' | jq -r . [0].Mountpoint`
# Use socat to listen to port 3307 and forward node.socket
sudo socat TCP-LISTEN:3307,reuseaddr,fork UNIX-CONNECT:${SOCKET_DIR}/node.socket 
```

Run a Unix socket proxy using TCP on the wallet machine

```sh
IP="10.20.0.201"
SOCKET_DIR=`docker volume ls | grep node-ipc | xargs -n2 sh -c 'docker volume inspect $1' | jq . [0].Mountpoint`
sudo socat UNIX-LISTEN:${SOCKET_DIR}/node.socket,fork,reuseaddr,unlink-early TCP:${IP}:3307
```

**Comment by johncooler** [comment]
> Yes it is because of security.

are you joking? 
For real, you need to learn basics of TCP/IP, firewalls, and authentications

the most ridiculous answer I have seen
