### ISSUE TITLE
Weird tx history and balance when force-resyncing

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#1567]
# Context

The force-resync endpoint allows artificially rolling back the wallet to (SlotId 0 0).

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | includes the #1559 fix  |
| Platform     | mac          |
| Installation |  Official FC with cardano-wallet manually replaced  |

# Steps to Reproduce

1. Launch Daedalus FC with a wallet
2. 
```
curl  -vX PUT https://localhost:50078/v2/byron-wallets/021028cf0b109aab8f4fde7dd124a89efeeb4ed8/tip \
       -H "Content-Type: application/json; charset=utf-8" \
       -d '{ "slot_number": 0, "epoch_number": 0 }' --http1.1 --cert $TLS/client.pem --cacert $TLS/ca.crt  |  jq
```

## Expected behavior

I'd expect:
1. <s>All tx history disappears</s>

But otherwise:
2. <s>All of the tx history becomes pending but otherwise don't change</s>

And always:
3. Tx history should be in sync with the wallet balance
4. The wallet balance should (here) be 0 immediately after force-resyncing

## Actual behavior

- Incoming txs disappear from history. Outgoing txs are turned to pending.
- The pending outgoing txs have the wrong dates
- The wallet balance does not match the tx history
- The wallet balance is not 0 at the start of the chain. The balance decreases to become more accurate while syncing, despite the wallet essentially only having _incoming_ transactions.
 

---

# Resolution 

---

# QA

**Comment by KtorZ** [comment]
- **Incoming txs disappear from history. Outgoing txs are turned to pending.**

This is the actual expected behavior. When rolling back, incoming txs are forgotten (and will eventually be re-discovered). On the contrary, outgoing txs may still be in a mempool and be accepted somewhere. Possibly, they'll end up invalid because they reference a no-longer existing UTxO. But it is so far up to users to cancel them. 
Later, we will add automatic re-submission of transaction, using a transaction scheduler. 

- **The pending outgoing txs have the wrong dates.**

This is also expected. The transaction is becoming pending at the precise time the rollback happened. 

- **The wallet balance does not match the tx history**
- **The wallet balance is not 0 at the start of the chain. The balance decreases to become more accurate while syncing, despite the wallet essentially only having incoming transactions.**

These two are actually much more interesting and do not look right. Although there are still pending transaction in the history, the checkpoint UTxOs should still be correct and so should the balance.

**Comment by Anviking** [comment]
The funds I see must be the change from the pending transactions (from the future): https://github.com/input-output-hk/cardano-wallet/blob/5333afc469294bfa74e07de3317578545661ea05/lib/core/src/Cardano/Wallet/Primitive/Model.hs#L321

_Wondering_:
Say we rollback a tx1, and spend its inputs on the new fork in tx2. tx1 is now invalid. Will tx1 still be pending, and will its change incorrectly contribute to the available balance? 🤔

**Comment by KtorZ** [comment]
Yes. Or at least, in Daedalus, because Daedalus shows the `total` balance, not the `available` one :/

**Comment by Anviking** [comment]
A similar-looking occurrence on the ITN without force-resync: https://input-output-rnd.slack.com/archives/CDM8B0AN9/p1591216845381400

**Comment by HeinrichApfelmus** [comment]
@Anviking The logic for keeping track of submitted transactions has changed a while ago. Is this issue still present?

**Comment by Anviking** [comment]
@HeinrichApfelmus It's difficult to test, both because I currently don't have a local synced node, and because the force-resync endpoint has been removed. Do you have an idea of how the effects of the changes in this context?

Off the top of my head:
- Force-resyncing has been removed, but perhaps something similar will be introduced in the future for DB migration. I'm not sure how the DB changes would interact with this.
- I imagine multiple pending txs spending the same TxIns still could lead to misleading (total) balances because of the change

**Comment by HeinrichApfelmus** [comment]
>  the force-resync endpoint has been removed. 

I see. In this case, I would simply like to close the issue in order to tidy up our issue list.

> but perhaps something similar will be introduced in the future for DB migration.

If we were to reintroduce this functionality again, I think the correct solution is to treat it as a rollback. The DB is now almost fully subservient to the `WalletState` data structure, where such behavior can be reasoned about.

> Say we rollback a tx1, and spend its inputs on the new fork in tx2. tx1 is now invalid. Will tx1 still be pending, and will its change incorrectly contribute to the available balance?

I think the available balance is computed from the total balance by subtracting unspent outputs can are inputs to pending transactions. This means that if an output has already been spent, it will not be subtract again.

**Comment by Anviking** [comment]
From the wallet spec; the wallet functions should still work similarly:

<img width="547" alt="Skärmavbild 2023-07-19 kl  17 11 04" src="https://github.com/cardano-foundation/cardano-wallet/assets/304423/c5cc333d-57e4-495e-9766-719eaf2fc45e">

> I think the available balance is computed from the total balance by subtracting unspent outputs can are inputs to pending transactions. This means that if an output has already been spent, it will not be subtract again.

The problems arise from the change being _added_ as part of the total balance. Rolling back to genesis would move outgoing txs to pending, and add up all their change, even though the first change output probably was spent by the second pending tx etc. Without some custom logic, the change from chained or conflicting txs could be added up in such a way that the `totalBalance` seems way too high.

> I see. In this case, I would simply like to close the issue in order to tidy up our issue list.

Fair enough, though I'm not convinced something similar could not happen again through long rollbacks, real or artificial ones.

**Comment by HeinrichApfelmus** [comment]
> Fair enough, though I'm not convinced something similar could not happen again through long rollbacks, real or artificial ones.

@Anviking and I have discussed this in a call and came to the following conclusion:

* In the presence of rollbacks, the definition of `totalBalance` actually needs to be adapted to account for sequence of pending transactions that spend each other's outputs. This is discussion in Section 7 of the [wallet specification][1].
* In the presence of expiration dates and rollbacks, `totalBalance` ceases to make sense — it becomes possible to create pending transactions that attempt to spend the same outputs even though each transaction spends from the available balance at the time of submission. Expiration dates are mentioned in Section 10.4 of the [wallet specification][1], but no full treatment is given.

After some thinking, I believe that a new notion of "minimum anticipated balance" in lieu of "total balance" might be suitable. I have created ticket ADP-3106 to revisit this.

  [1]: https://github.com/cardano-foundation/cardano-wallet/blob/master/specifications/wallet/formal-specification-for-a-cardano-wallet.pdf
