### ISSUE TITLE
Byron wallet restoration not possible on latest versions

### ISSUE THREAD

**Issue by thevictor13** [cardano-foundation/cardano-wallet#1646]
# Context
 
Back in december I have restored two Byron wallets successfuly, then I migrated one of them. Last month (and today) I tried migrating the other one, unsuccessfully. I run into the same issue as described here: #1552. On that issue there is a workaround mentioned. One needs to delete and restore the Byron wallet. However restoration of said wallet also fails.
 

| Information  | -                                                     |
| ---              | ---                                                   |
| Version       | 2020.4.7 (git revision: cff0e391985887f60b9076aace207674bef6a2b4), jormungandr 0.8.15 |
| Platform     | Linux, the least          |
| Installation | From Github Release            |

# Steps to Reproduce

```
  $ curl -X POST http://localhost:8090/v2/byron-wallets/random \
  -H "Content-Type: application/json" \
  -d '{
    "name": "MyByronWallet",
    "passphrase": "MySecurePassphrase",
    "mnemonic_sentence": [
      "survey",
      "wonder",
      ...
  ]}'
```

## Expected behavior

returns 
```
{ ..., "id": "aa129a07d1ce083e67597348f1788747a034686e", ... }
```

## Actual behavior
 
returns 
```
{"code":"bad_request","message":"wallet id should be a hex-encoded string of 40 characters"}
```

---

# Resolution 

---

# QA

**Comment by KtorZ** [comment]
Hi Viktor. There has been a breaking change in the API. The style of wallet has moved from path parameters to body parameters. So instead of `http://localhost:8090/v2/byron-wallets/random` you should hit `http://localhost:8090/v2/byron-wallets/` and, the body should now contain a `style` field set to `random`. 

See also: https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/postByronWallet
