### ISSUE TITLE
Expire transactions when TTL reached

### ISSUE THREAD

**Issue by rvl** [cardano-foundation/cardano-wallet#1838]
# Context

ADP-93 Transaction scheduler

Introduce a time-to-live (TTL) value for transactions, stating that the transaction must be included in the blockchain before a certain slot and simply dropped otherwise.

# Decision

- TTL value is a number of slots, and hardcoded initially.
- The Tx expiry slot is calculated when the transaction is created, and recorded in the DB with pending transactions.
- Add a new TxStatus "Expired", which means that the TTL has been reached.
- In the wallet layer, when applying blocks, check the expiry slot of pending transactions. Any expired transactions are removed from the pending set and marked with Expired state.
- Tx expiry is not something that can be rolled back.

# Acceptance Criteria

- Transaction expiry must be the time when the transaction was created plus the TTL. 
- Transactions must not be still pending after their TTL has been reached.

---

# Development 

As above.

# QA 

1. Integration tests are added in `lib/core-integration/src/Test/Integration/Scenario/API/Shelley/Transactions.hs`
    - TRANS_TTL_01
    - TRANS_TTL_02
    - TRANS_TTL_03
    - TRANS_TTL_04
    - TRANS_TTL_DELETE_01

**Comment by jonathanknowles** [comment]
@rvl 

> Add a new transaction state "Expired", which means that the TTL has been reached.

Just to clarify, is the intention to represent this as an additional constructor on `TxStatus` (and corresponding DB field `txMetaStatus`)?

**Comment by rvl** [comment]
@jonathanknowles Yes, I think so, but after further digging this decision may change.

**Comment by HeinrichApfelmus** [comment]
This is a very old issue which has been implemented.

The design has changed compared to the issue description. The [current design][1] is that

* `Expired` transactions can be rolled back, because they can actually still be included in the blockchain after a rollback.
* The pending transactions are kept in a separate database table from the transactions that are in ledger.

[1]: https://github.com/cardano-foundation/cardano-wallet/blob/4d1575023d29be39cfb7867f010c6c6f0de61243/specifications/Cardano/Wallet/Submissions/design.md
