### ISSUE TITLE
Metadata submited with json will allow multiple pools creating same ticker 

### ISSUE THREAD

**Issue by SViksha** [cardano-foundation/cardano-wallet#1876]
# Context
 
Metadata for wallet is accepted via json file which will allow multiple pool to use same Ticker . Also that will allow pool to high-jack the most famous pool to defame them. We have build good reputation on the ITN and would like to keep same Ticker but there are chances that other pool operator may high-jack the Ticker. 

# Resolution 

Allow way to transfer the  ITN ticker by signing main net ticker with ITN pool secrete key and have a separate hash  for Ticker signed by node key to avoid duplication.

**Comment by KtorZ** [comment]
Unfortunately, there's _"nothing"_ the wallet can do about it :/ . There's no rules enforced by the ledger about the uniqueness of the ticker for this generates many other problems (suppose for a second that the ticker are unique, what prevents an attacker from registering all known tickers from the ITN before, if not everyone, most legit pool operators?)

The problem isn't quite simple but after many debates, the choice was made to NOT make the ticker unique and simply rely on pools being able to advertise correctly their identity. Daedalus will soon (if not already :thinking: ?) show the unique pool id as part of the UI, next to the ticker, and it's recommended for pools to unambiguously advertise their pool ID to their community, so that people can double-check and find the right ticker with the right pool id.

**Comment by KtorZ** [comment]
There could be an ad-hoc process however for _proving ownership_ of metadata (like you're suggesting as a resolution). This would have to be implemented by any client software  consuming metadata. If you find time for it, I'd highly suggest to draft a [CIP proposal](https://github.com/cardano-foundation/CIPs) about it, from the top of my head I believe that something in light of what you just mentioned would work:

- Add pool's public key to the metadata
- Add a signature of the file to the (canonicalized) metadata file without signature (or host the signature elsewhere) 

With this, a wallet software could show that a metadata is _verified_ or _trusted_ but it'd still require to have a prior knowledge of all ITN pools and keys :/
