### ISSUE TITLE
Stakepools are not shown immediately in wallet after they are registered. 

### ISSUE THREAD

**Issue by piotr-iohk** [cardano-foundation/cardano-wallet#1930]
# Context
 https://input-output-rnd.slack.com/archives/GBT05825V/p1595052799003600

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | `2020.7.6 (git revision: cf3847dd08d1c1848c675a1ee94ae12c1d85aadf)` |
| Platform     | all         |
| Installation | Daedalus / From source          |

# Steps to Reproduce

1. Register a stake pool in `epoch` (stake pool registered successfully and visible in the ledger state)
2. Run list stake pools in the wallet.

## Expected behavior

Stake pool that was registered in `epoch` should be immediately visible in the wallet in the same epoch.

## Actual behavior
 
Stake pool is visible in `epoch + 2`

---

# Resolution 

---

# QA

**Comment by Anviking** [comment]
Copying from slack for visibility:
> I believe we should also make sure to, in the case pools have the same non-myopic rewards (they might all have 0 in the first epoch?), then order them randomly based on a user-specific seed. We did this for jormungandr (for the first epoch).
>
> Think this is mentioned in the delegation design spec

even if that might technically be a separate ticket

**Comment by KtorZ** [comment]
This is a necessary limitation until we are done with the retirement certificates story. As a matter of fact, we currently rely on the ledger's state to know whether pools are active or not.

We are processing and discovering pool's registration certificates ourselves, indeed but I am not quite sure about the status of the retirement discovery and handling at the moment? cc @jonathanknowles

**Comment by jonathanknowles** [comment]
@KtorZ wrote:

> This is a necessary limitation until we are done with the retirement certificates story. As a matter of fact, we currently rely on the ledger's state to know whether pools are active or not.
> We are processing and discovering pool's registration certificates ourselves, indeed but I am not quite sure about the status of the retirement discovery and handling at the moment?

I'll try to shed some light on this.

## Current status

When constructing the list of pools to return in `GetStakePools`, we currently rely on **two data sources**:

1. Our database record of _registration_ and _retirement_ certificates.
2. The data returned by local state query (via `getStakeDistribution`).

As for the former (our database record), we update this whenever we process a new block, and **we currently record all registration and retirement certificates**, together with the _order_ in which we see them. So from the perspective of populating the database with the correct data, the work for [ADP-313](https://github.com/input-output-hk/cardano-wallet/milestone/89) is already complete (apart from any further integration test work).

As for the latter (data returned by LSQ), the work for [ADP-313](https://github.com/input-output-hk/cardano-wallet/milestone/89) has not materially changed the way this code works.

## Current behaviour of the `ListStakePools` endpoint

When including a pool within `ListStakePools`, there are three distinct potential cases:

| DB data present? | LSQ data present? | Included in `ListStakePools`? |
|---|---|---|
| :heavy_check_mark:  Yes | :heavy_check_mark: Yes | :heavy_check_mark: We can construct a complete `ApiStakePool` object. |
| :negative_squared_cross_mark: No | :heavy_check_mark: Yes | :heavy_check_mark: We can construct an `ApiStakePool` object, but the **optional fields will all be missing**. |
| :heavy_check_mark: Yes | :negative_squared_cross_mark: No | :negative_squared_cross_mark: We are unable to construct an `ApiStakePool` object at all. |

For more information, see the function [`combineDbAndLsqData`](https://github.com/input-output-hk/cardano-wallet/blob/master/lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs#L207
), which merges DB data with LSQ data.

## Current behaviour relating to pool retirement

As mentioned above, we record all registration certificates and retirement certificates _in the order that they appear_ (which is well-defined, even for the case where multiple certificates appear in the same block or even the same transaction).

The wallet currently treats a retirement certificate as though it _augments_ the latest-known registration for a pool. In other words, the retirement data is just an "extra piece of data" that we bolt on to the registration data included in a `ApiStakePool` value.

There is the added complication of re-registration: a later registration certificate can override an earlier retirement certificate. In this case, we take care to NOT indicate that a pool is retiring.

We handle this by only calling [`combineChainData`](https://github.com/input-output-hk/cardano-wallet/blob/5161dde504e3326b47833de30e2c462348d8ab96/lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs#L284) with the result of [`readPoolLifeCycleStatus`](https://github.com/input-output-hk/cardano-wallet/blob/5161dde504e3326b47833de30e2c462348d8ab96/lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs#L324), which does the work of determining the order of precedence of certificates for us.

## Current DB garbage collection behaviour

We currently **don't perform any garbage collection** of data relating to retired pools from the database. (Though this is planned in https://jira.iohk.io/browse/ADP-376).

So if a pool **_disappears_** from the `ListStakePools` listing, it is because there is no longer LSQ data available for that pool.

**Comment by KtorZ** [comment]
So, now that we store retirement certificates, we could change this particular behavior here:

https://github.com/input-output-hk/cardano-wallet/blob/5161dde504e3326b47833de30e2c462348d8ab96/lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs#L205-L207

to not drop pools that we are aware of but aren't active yet. The question is what do we do with:

a. The non myopic member reward
b. The relative owned stake 
c. The saturation

a)
In the past, we were dealing with ranking and desirability, which were calculations based on the performance. For new pools, we used to set the performance to the average performances of top existing pools, to give newcomers a chance / some visibility. Now that we don't have this much control and I don't think that using an average non-myopic member rewards would do here (because it completely disregard cost & margin which could be incredibly high...) 

b) 
Until the pool becomes active / listed in the LSQ, the only stake it can have would be its own pledge :thinking: ... Although there's also no guarantee that operators did honor their pledge. Regardless, the pledge wouldn't be delegated before the next epoch at least. So perhaps `0` is a more sensible default here.

c) This can be calculated from the relative stake (and the desired number of pools). So solving b. also solves c.

**Comment by piotr-iohk** [comment]
>This is a necessary limitation until we are done with the retirement certificates story. As a matter of fact, we currently rely on the ledger's state to know whether pools are active or not.

I don't know if this is equivalent but pool **is** visible in the ledger state immediately after it is registered, at least it is visible when querying with `cardano-cli`:
```
$ cardano-cli shelley query ledger-state --testnet-magic 42 | grep QAPool3

   "url": "https://piotr-iohk.github.io/adrestia-qa-board/QAPool3.json"
``` 
But maybe it is not marked as "active" yet...

> So if a pool disappears from the ListStakePools listing, it is because there is no longer LSQ data available for that pool.

So from the observation retired pool is no longer visible in the LSQ data since `e + 4`, where `e` is the retirement epoch -> https://github.com/input-output-hk/cardano-wallet/pull/1931#discussion_r457417183

**Comment by jonathanknowles** [comment]
@KtorZ wrote:
> a)
> In the past, we were dealing with ranking and desirability, which were calculations based on the performance. For new pools, we used to set the performance to the average performances of top existing pools, to give newcomers a chance / some visibility. Now that we don't have this much control and I don't think that using an average non-myopic member rewards would do here (because it completely disregard cost & margin which could be incredibly high...)

> b)
> Until the pool becomes active / listed in the LSQ, the only stake it can have would be its own pledge thinking ... Although there's also no guarantee that operators did honor their pledge. Regardless, the pledge wouldn't be delegated before the next epoch at least. So perhaps `0` is a more sensible default here.

> c) This can be calculated from the relative stake (and the desired number of pools). So solving b. also solves c.

So it would seem that the only sensible default for each of these values is **zero**?

I've coded up a PR that does this here: https://github.com/input-output-hk/cardano-wallet/pull/1936

**Comment by jonathanknowles** [comment]
@piotr-iohk 

> So from the observation retired pool is no longer visible in the LSQ data since `e + 4`, where `e` is the retirement epoch -> [#1931 (comment)](https://github.com/input-output-hk/cardano-wallet/pull/1931#discussion_r457417183)

Assuming we use the approach suggested above (to use default values for LSQ data when LSQ data is not available), this would mean that retired pools no longer disappear from the list returned by `ListStakePools`, unless we **either**:

- exclude retired pools from the `ListStakePools` listing (by filtering out pools where `currentEpoch >= retirementEpoch`); **or**
- garbage collect retired pools from the pools database (https://jira.iohk.io/browse/ADP-376).

(or some combination of the above: we would probably wish to provide a grace period before we garbage collect data relating to pools that have retired, to protect against rollbacks)

**Comment by KtorZ** [comment]
@jonathanknowles IMO, it's not a `or` statement, but a `and then`, where the first one (exclude retired pools from listing) MUST be done as part of the retirement certificates story. We should not show pools that are retired (which I believe we do not currently because of the way we combine data from the LSQ, a retired pool wouldn't show up). Yet if we change this behavior such that _some pools_ not returned by the LSQ are now combined with default values, then we have to be careful about what pools (i.e. not show retired pools!).

**Comment by jonathanknowles** [comment]
@KtorZ wrote:
> (exclude retired pools from listing) MUST be done as part of the retirement certificates story.
> We should not show pools that are retired.

As far as I know, this requirement is _not yet_ an explicit part of [ADP-313](https://jira.iohk.io/browse/ADP-313), which merely states:

> _"As a wallet user, I want to check if and when a stakepool will retire, so that I can make an informed choice about which stakepool to delegate my stake."_

In other words the story doesn't specify a preference between:

1. keeping retired pools in the list, but indicating that they are retired; and
2. removing retired pools from the list.

Of course, if we wanted to remove pools from the list returned by `ListStakePools`, we could just filter out pools where `currentEpoch >= retirementEpoch`.

**@KtorZ Do you agree with this filtering approach?** If so, I'll add a ticket to the milestone (and likely tackle it right away).

As for garbage collection of retired pool entries from the database, we have a story for that here:
https://jira.iohk.io/browse/ADP-376

**Comment by KtorZ** [comment]
> As far as I know, this requirement is not yet an explicit part of ADP-313

Make it so then :upside_down_face: ! It should've been.

 > Of course, if we wanted to remove pools from the list returned by ListStakePools, we could just filter out pools where currentEpoch >= retirementEpoch.

Yes, though this filtering needs to happen inside a database query and NOT in-memory after fetching pools.

**Comment by jonathanknowles** [comment]
@jonathanknowles wrote:
> > As far as I know, this requirement is not yet an explicit part of ADP-313

@KtorZ responded:
> Make it so then upside_down_face ! It should've been.

Done! 

I've added the following requirement to those listed in [ADP-313](https://jira.iohk.io/browse/ADP-313):

> **Prevent listing of retired pools**: The wallet _must not_ include pools that have already retired in the list of known pools returned by the API `ListStakePools` operation.

Also:
> Yes, though this filtering needs to happen inside a database query and NOT in-memory after fetching pools.

:+1:

**Comment by piotr-iohk** [comment]
LGTM. Pool is immediately visible in wallet after registering. You can also delegate to it.

Checked on MC4:

```
241: 60691367442bb67ba7a009260a424b59d20dd90e880571bfb1ff0fab
Margin: 5%
Cost: 340000000 lovelace
Pledge: 1000000000 lovelace
Metrics:
  Saturation: 0
  Non-myopic member rewards: 0 lovelace
  Produced blocks: 0
  Relative stake: 0%
Metadata:
  Homepage: https://github.com/input-output-hk/adrestia
  Name: Adrestia QA
  Ticker: QAQA1
  Description: The pool that tests all the pools!!!
```
