### ISSUE TITLE
Pools fetching and fees calculation for not null withdrawal param takes 3-10mins

### ISSUE THREAD

**Issue by Fell-x27** [cardano-foundation/cardano-wallet#2004]
# Context
 
 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      |  v2020-08-03 |
| Platform     | Linux |
| Installation | From binaries |

# Steps to Reproduce

1. Try to calculate fee with active "withdrawal" param or try to fetch pools list  **in the mainnet**.
2. ...
3. PROFIT!

## Expected behavior

Waiting for couple seconds for fee calculation and 10-20 seconds for pools (around 800 for now).

## Actual behavior
 
You can have some coffee and watch something funny on the YouTube before response.

## Comment

Pools/fees fetching takes up to 10 mins, but, actually in pool's case it's not a problem - I do it as background task and then just  put it to a caching layer. So, at application level pools fetching takes no time for users. But fees are killing the application. I can't prefetch them by obvious reason.
So It's impossible to implement rewards withdrawal for the mainnet because of this issue. 

But I've submitted both problems because looks like they a related.
---

# Resolution 

---

# QA

**Comment by KtorZ** [comment]
@Fell-x27 would you mind opening two separate bug tickets for these two separate issues please :pray: 

Regarding pool fetching, are you doing this _while_ syncing? (cf: https://github.com/input-output-hk/cardano-wallet/issues/1846). One of the problem regarding pools listing is that, in order to reply to such request, cardano-wallet needs a few information from the node it's connected to and, the node won't reply to any request regarding the Ledger state until it is within k blocks from the network tip (where k stands for the security parameter here, 108 in the Shelley era). Which makes a lot of the queries look _slow_. 

As for fees, this looks indeed quit abnormal. May you open a separate ticket for this one and if possible, provide your UTxO summary / statistics? If not, perhaps simply an order of magnitude of your wallet's size?

**Comment by Fell-x27** [comment]
>Regarding pool fetching, are you doing this while syncing? 

No. The node and wallets are perfectly synced. But node fetches pools list up to 10 mins.

>May you open a separate ticket for this one 

Sure

> and if possible, provide your UTxO summary / statistics? If not, perhaps simply an order of magnitude of your wallet's size?

I can't. But  tested it by myself. It doesn't depend on wallet size\UTxO amount\Reward amount. The same result for funded wallet without reward, rewarded without UTxO, and even for zero-balanced one.

Probably, both problems are related with the **count of wallets** because there are dozens. But only pools and fees with withdrawal included are so slow.

**Comment by Fell-x27** [comment]
@KtorZ , ^^^
