### ISSUE TITLE
Call `removeRetiredPools` from `monitorStakePools`.

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#2019]
# Context

As part of the work to garbage collect retired pools from the database, we need to periodically _initiate_ the garbage collector.

# Decision

Within `monitorStakePools`, at appropriate points call [`removeRetiredPools`](https://github.com/input-output-hk/cardano-wallet/issues/2018) with epoch number _**e**_, where:

> _**e**_ = _**e**_<sub>current</sub> − 2.

The choice to wait two epochs after retirement is a conservative one, and ensures that we will never garbage collect pools that are still within the rollback window.

# Acceptance Criteria

- [x] The pool monitoring code _must not_ call `removeRetiredPools` with an epoch number that is within the rollback window.
- [x] Any calls to `removeRetiredPools` _must_ be logged to assist with debugging.

# Development 

- https://github.com/input-output-hk/cardano-wallet/pull/2057

# QA

See:
- #2016 
- #2017

**Comment by jonathanknowles** [comment]
Hi @piotr-iohk 

This was finished some time ago, but I forgot to move it into the QA bucket. My apologies!

Hopefully there is nothing more to do, but let me know if you spot anything.

If all is okay, then we can also close https://jira.iohk.io/browse/ADP-376.

**Comment by piotr-iohk** [comment]
@jonathanknowles, so I'm looking into integration tests while there are running and we have there 4 pools initially with one of them that is scheduled to be retired in epoch 3. The pool is no longer displayed in list pools since epoch 3 which is OK. I expected however that since epoch 5, data related to this retired pool will be removed from DB, but I still see bits of this pool in DB in epoch 5 and onwards:
E.g. (there are 4 pools and I was expecting 3)

![Screenshot from 2020-09-15 09-26-36](https://user-images.githubusercontent.com/42900201/93179402-ebd2a780-f735-11ea-9798-b2bb46a5a6b4.png)

![Screenshot from 2020-09-15 09-26-51](https://user-images.githubusercontent.com/42900201/93179423-f2611f00-f735-11ea-9a0e-930009bc100f.png)

![Screenshot from 2020-09-15 09-27-01](https://user-images.githubusercontent.com/42900201/93179427-f4c37900-f735-11ea-8266-b096f69e1b89.png)

![Screenshot from 2020-09-15 09-27-09](https://user-images.githubusercontent.com/42900201/93179436-f7be6980-f735-11ea-9632-7793866cb197.png)

![Screenshot from 2020-09-15 09-28-52](https://user-images.githubusercontent.com/42900201/93179443-fab95a00-f735-11ea-8028-6f1298c4ddc2.png)

Shouldn't this data be garbage collected? (Or maybe I'm misunderstanding something.)

**Comment by jonathanknowles** [comment]
Hi @piotr-iohk.

Do you have a copy of the log output for that test run? It will be useful to see whether there are any entries like this:

```
Performing garbage collection of retired stake pools. Currently in epoch 5. Removing all pools that retired in or before epoch 3.
```

**Comment by piotr-iohk** [comment]
I have set `MsgStakePoolGarbageCollection{} -> Info` for the run [here](https://github.com/input-output-hk/cardano-wallet/blob/master/lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs#L657), but indeed, there is no such message "Performing garbage collection of retired stake pools...".

Here are the logs from the run, up to epoch 11.
[tests.log](https://github.com/input-output-hk/cardano-wallet/files/5231848/tests.log)

**Comment by piotr-iohk** [comment]
lgtm.

To sum up:
 - Pool that is scheduled to retire in epoch n, is no longer visible in `GET /stake-pools` since epoch n.
 - Garbage collection happens once per epoch. Data of pool that is retired in epoch n is garbage collected in epoch n + 2.
 - All data of retired pool is garbage collected from stake-pools.sqlite except its pool_metadata, as the same metadata can be utilized by many pools.
