### ISSUE TITLE
The handling fee is higher than the transfer amount

### ISSUE THREAD

**Issue by ghost** [cardano-foundation/cardano-wallet#2259]
![image](https://user-images.githubusercontent.com/38401802/96664616-c4e74100-1385-11eb-9d77-424261d1e6bc.png)

**Comment by ghost** [comment]
28db52dcebadd7dc5e9f2c91aff584b9bc05aaeedc15e05bdd35b077a7912d3e

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/38401802/96671699-04695980-1395-11eb-8aa3-a6ded5e45ea6.png)

**Comment by piotr-iohk** [comment]
Hi @satonz, what was the initial balance of the wallet before the transaction? If it was ~2.136429 then I think that'd be expected.
The reason is `minUtxOValue` protocol setting that is currently set to 1 ADA which basically prevents to have UTxO lower than this, hence there cannot be a balance on the wallet that is smaller than 1 ADA.

When you send 1 ADA from a wallet with balance that is 2.136429 ADA, the fee of that operation would be initially calculated as ~0.17 ADA. The fee would be deducted from the remaining balance i.e. 1.136429 - 0.17 which leaves less than 1 ADA on the wallet. As protocol does not allow for this, unfortunately all the remaining balance needed to be added to the fee.

**Comment by ghost** [comment]
The current balance of the wallet is over 10ADA,

**Comment by KtorZ** [comment]
@satonz may you please describe what the actual issue is? What behavior would you expect and also, some reproduction steps?

**Comment by ghost** [comment]
I think this is a Bug. I also charged 1ADA for transferring 1ADA, and the current balance of my wallet is more than 10ADA

**Comment by ghost** [comment]
Poundage shouldn't be so much

**Comment by KtorZ** [comment]
As @piotr-iohk explained above, Cardano is a UTxO blockchain. Your balance is therefore constructed out of several pieces of fixed value also called "coins". When making a transaction, you cannot take part of a coin, you have to spend it fully (as you would do paying to a real merchant with coins from your wallet) and get back some change. 

Yet, in order to avoid a certain class of attack, the network does not allow the creation of coins output that are too small, that is at the moment below 1Ada. 

Therefore, when selecting a coin that will result in a change output that is too small and can't be created, the wallet currently simply add the surplus as fees which is what you're observing here. There are plans in the future to make this behavior slightly more complex, but generally better for end users. At the moment, it is expected. 

Closing this ticket as it is describing a perfectly valid and expected behavior.
