### ISSUE TITLE
wallet api

### ISSUE THREAD

**Issue by ghost** [cardano-foundation/cardano-wallet#2276]
How do I get the address balance and the exact transaction fee

**Comment by ghost** [comment]
The wallet doesn't seem to provide an API at this time

**Comment by rvl** [comment]
Hi @satonz,

1. **Address Balance** There is currently no API to get the balance at a single address. You can get the balance for the entire wallet, or for a single account of the wallet. You may be able to work around this by using the transaction history API endpoint, and calculating the address balance yourself.

2. **Exact transaction fee** The transaction fee can vary, so the API only provides an estimate. The reason is that cardano-wallet uses random coin selection to build transactions. This is actually the best coin selection method to minimize dust coins (and therefore average fees). But the fee depends on which coins are randomly selected to fund the transaction.

   If you absolutely need to know the exact fee ahead of time, the `/v2/wallets/{walletId}/coin-selections/random` endpoint can give you a coin selection for the payment. Then you can build and sign the transaction with the [cardano-tx](https://github.com/input-output-hk/cardano-transactions) CLI. Then you can submit it with the `/v2/proxy/transactions` endpoint.

**Comment by ghost** [comment]
cardano-graphql The relevant information is available, but I find that the repository is constantly changing and may be unstable

**Comment by ghost** [comment]
@rvl

**Comment by rvl** [comment]
Hi @satonz, cardano-graphql may be more stable if you stay with released versions.

**Comment by KtorZ** [comment]
cardano-graphql is a stable product and we are doing our best to minimize the amount of changes in the API from a release to another. 

> I find that the repository is constantly changing

That is the case for cardano-wallet too :). Both repositories, as any project in Cardano, are changing at a frenetic pace. Yet again, we do our best to limit the integration efforts from the user's side. 

@satonz , do you mind if I close this ticket now?
