### ISSUE TITLE
cardano-node build wth ghc-8.6 not with ghc-8.10

### ISSUE THREAD

**Issue by laplasz** [cardano-foundation/cardano-wallet#2481]
Hi There!

Latest release 1.25.1 [assets](https://github.com/input-output-hk/cardano-wallet/releases/download/v2021-01-28/cardano-wallet-v2021-01-28-linux64.tar.gz) has a cardano-node binary compiled with ghc-8.6
However the [installation guide](https://docs.cardano.org/projects/cardano-node/en/latest/getting-started/install.html) suggests that latest version of ghc should be used - 8.10.3

thanks,

**Comment by rvl** [comment]
Hi, thanks for your question.

We are still building cardano-wallet and cardano libraries with ghc-8.6.3.
When we have a moment we will switch to ghc-8.10, but for now ghc-8.6.3 is working fine.
cardano-node can build with ghc-8.6.3, and this is what we test the wallet against.
In future, cardano-node will probably stop compiling with ghc-8.6, because nobody is using it, so that's probably why the docs say 8.10.3.
