### ISSUE TITLE
[feature] Newly created wallet should not need to sync history

### ISSUE THREAD

**Issue by jonathancross** [cardano-foundation/cardano-wallet#2545]
[moved here from [daedalus#2415](https://github.com/input-output-hk/daedalus/issues/2415)]

When creating a new wallet in an instance of Daedalus that has already synced older wallets, Daedalus will immediately go through a long, slow process of syncing:

> The balance and transaction history of this wallet is 34.87% synced with the blockchain.

This makes no sense as there is verifiably zero transactions and zero balance on a newly generated wallet.

Instead, Daedalus should recognize that this wallet is _already synced_ and skip unnecessarily looking up history.

**Comment by rvl** [comment]
Hi @jonathancross, thanks for the report.
Yes, the cardano-wallet backend API does not make a distinction between creating a wallet and restoring a wallet.
I believe that your suggestion in #2544 would fix this issue.
Because if Daedalus knows that it has generated a fresh random mnemonic, then it could set the wallet birthday to the current time, and the new wallet would be available for use immediately.

**Comment by jonathancross** [comment]
If / when #2544 is implemented, this would sill need to be used when syncing.
Shouldn't that be an open task here or in Daedalus?
