### ISSUE TITLE
[feature] Support reward history API

### ISSUE THREAD

**Issue by JasinYip** [cardano-foundation/cardano-wallet#2547]
As @feraldruid22 and @nikolaglumac talked about the feature of reward history displaying on wallets(e.g. Daedalus) in Daedalus issue(https://github.com/input-output-hk/daedalus/issues/2347). 

We might need this project to offer an API to implement the feature:

> The number of staking rewards (at least the last 10 epochs) should be displayed in a table with the stake pool name so we can track the exact amount of rewards per epoch. Right now it is just an overall reward what you made.

**Comment by KtorZ** [comment]
Hi, this is unfortunately not possible due to the very nature of the wallet. In order to calculate rewards and reward history, one needs to maintain the entire ledger state. However, the wallet only has a user-centric view of the ledger state, that is, it only maintains UTxO that belongs to it. 

Note that even the node / ledger isn't able to go as far back in the past. The UTxO is an ever evolving graph, and it gets folded along the way with every new block application. Maintaining an history of past UTxO state would be very costly on storage and memory. So the ledger keeps nothing more than what's necessary to accommodate chain forks and to calculate the leader schedule, but nothing beyond. 

We've however discussed this feature several time within teams and this is something which would better be done by an explorer-like software, which has actually access to the entire chain history.
