### ISSUE TITLE
Feature Request: Ability to re-fetch a specific pool's metadata using ID

### ISSUE THREAD

**Issue by rdlrt** [cardano-foundation/cardano-wallet#2551]
The issue originates as a requirement on Daedalus end, but since pool queries are made against `cardano-wallet` , I believe the issue belongs here.

Allow users who already know a pool ID they want to delegate to, to be able to refresh/download the metadata independently of SMASH server status.

Currently due to various design complications/networking reasons, a pool's metadata may be fetched and not be refreshed for a while (mostly due to the way SMASH works, but also we save local pool metadata). This means at times delegators have to wait for days if not hours for a correctly registered pool metadata.

The feature request is to allow a specific pool ID to be refreshed directly from wallet layer - without having to wait indefinitely upon when SMASH server will correct the information (while we can elect a different smash server from daedalus, there will not be a way to add any community instances to pre-populated fields in UI layer as part of default installation, and users will not be bothered looking around for custom smash server).

**Comment by rvl** [comment]
Hi, what's your exact problem here?
Do you have a newly registered pool, or an existing pool for which you would like to change the metadata?

**Comment by rdlrt** [comment]
@rvl - I do not have a problem myself, but across community channels there are 100s of cases where pool operators who either update metadata or register new pool - at times (due to limitations on SMASH now, before used to be wait times on wallet) often end up getting frustrated and anxious because the updates are not realtime. In fact it is becoming a common caution to not touch the pool metadata knowing the delays/inconsistencies with the Daedalus -> Wallet -> SMASH architecture.

*Note that we're not talking about mismatch of metadata hash or specific pool ID having multiple hash against same URL etc.

Hence, I phrased it as a feature request (as against any bug - since things are working as they were developed).

**Comment by glitch40** [comment]
If an operator updates anything on their existing pool meta, even if everything is correct metadata hash is correct, no url conflict or cache issues, it can still be hours or days for the wallet to update and sync. This new update leaves pools left in the "unknown" status and missing from the wallet UI for sometimes days it appears Daedalus has cached the old information and is conflicting with the new update which leaves the pool in extended unknown state. We've had several reports of this issue and they are increasing.  

Instead of triggering a full refresh on metadata which increases load and takes close to an hour to complete currently. I believe the solution / feature being requested is a direct refresh of the db  for a specific known pool at wallet layer itself (ex: for Daedalus users, additional button next to search to refresh pool info using metadata URL instead of SMASH) vs waiting on smash to update currently (which can be unknown ETA), or trigger a refresh of pool DB (which could take hours).

**Comment by rvl** [comment]
The cardano-wallet release this week will contain PR #2432 which will make refreshing all metadata faster.
If pool operators need to quickly check that their metadata looks correct then they could disable SMASH.
I do not know why the SMASH server introduces long delays.
If not otherwise busy, the wallet should fetch new metadata fairly promptly after it finds a registration certificate with a new metadata hash.
