### ISSUE TITLE
Origin address sometimes does not show the input address in the input transaction json

### ISSUE THREAD

**Issue by LuisCRSousa** [cardano-foundation/cardano-wallet#2617]
The Input address shows in the testnet explorer but sometimes it doesn't in the cardano-wallet transaction json.

The first image shows the input address for transaction id: 0e9fb584d12bf70964d54a7ab26ddbe3e6a301b929767662a2b8619345a8595b
![02643009ef0c5e42a9e30aaa2949aae5164aff723fd0b66ac5e84d38835b5612](https://user-images.githubusercontent.com/8472158/115120701-b8474c80-9fa6-11eb-957e-83e51f8c2cd6.png)

The second image don't show the input address for transation id: 02643009ef0c5e42a9e30aaa2949aae5164aff723fd0b66ac5e84d38835b5612
![0e9fb584d12bf70964d54a7ab26ddbe3e6a301b929767662a2b8619345a8595b](https://user-images.githubusercontent.com/8472158/115120704-bed5c400-9fa6-11eb-8b5d-908d20b0fc19.png)

**Comment by KtorZ** [comment]
The wallet can only show inputs details for transactions it knows of. That is the case of all outgoing transactions (because all inputs belong to the wallet), and generally not the case for incoming transactions (although, a transaction from the wallet to itself consuming rewards may be marked as incoming, and inputs fully known). 

This is mentioned in the relevant section of the API documentation:

![Screenshot from 2021-04-17 20-11-54](https://user-images.githubusercontent.com/5680256/115122662-665bf200-9fb9-11eb-8bd6-3da868833967.png)

**Comment by wout** [comment]
We had the same issue. Sometimes the addresses are present; other times, they are not. We had this even with two equal transactions on testnet. Both with the same amount. Both from the same source wallet to the same destination wallet. They were about 20 minutes apart. In the first transaction, the input address was missing. But in the second transaction, it wasn't.

On testnet, it's there in most of the cases. I mean, we had about 130 test payments where it was, and just one not. On mainnet, it's a different story. There we had about 80% without and 20% with an address.

It feels like an odd inconsistency for an API. Why would the input address be sometimes present and sometimes not? Why is it even there if you can't rely on the data? Then it's just taking up space and bandwidth. Was that a conscious choice? Or is it a transitional situation?
