### ISSUE TITLE
Issues with wallet containing many unique native assets

### ISSUE THREAD

**Issue by falassiry** [cardano-foundation/cardano-wallet#2622]
Sharing some issues I am facing with an NFT focused wallet which contains more than 700 different unique native asset NFTs.

For almost any send transaction, the "calculating fees" step can take from 1 minute to sometimes up to 10 minutes until a transaction fee is shown and I can click send.

Sometimes, this ultimately leads to a failure to complete transaction after entering a correct spending password.

The transaction fees are typically in the 1.7 ADA range right now. I presume it is due to the UTXO nature of moving across all the tokens. However, sometimes, especially after fresh restart of the wallet, it only asks for the usual transaction cost of around 0.17 ADA.

In all cases, my bigger concern is usability rather than transaction costs.

Are these intended consequences? Can I keep my wallet usable as-is or am I in a situation where I am recommended to spread the tokens on multiple wallets?

Thanks.

**Jira ticket:** ADP-890

**Comment by piotr-iohk** [comment]
@falassiry thanks for reporting.

Would you mind telling how many utxos has your wallet? You can check in Daedalus by going to 'More -> Wallet UTXO distribution' for the wallet. It says there: "This wallet contains X ADA in **N** UTXOs"

**Comment by falassiry** [comment]
71 UTXOs.
65 of them between 1 and 10 ADA.

**Comment by jonathanknowles** [comment]
> The transaction fees are typically in the 1.7 ADA range right now. I presume it is due to the UTXO nature of moving across all the tokens. However, sometimes, especially after fresh restart of the wallet, it only asks for the usual transaction cost of around 0.17 ADA.

@falassiry The variation in transaction fee is likely to be due to the random nature of the wallet's coin selection algorithm. When selecting coins from your wallet to make a payment, the algorithm selects randomly, until we've got enough to cover the target quantity of each asset. (The algorithm also tries to select a little more of each asset, in order to generate "nice" change values to give back to the wallet, but this only happens if there is an excess. If you have exactly the right amount of each non-ada asset, then that's also good enough.)

For this reason, I suspect that reduced transaction fee you saw is unlikely to be affected by restarting the wallet. (Though if it is, that would be very surprising.)

**Comment by falassiry** [comment]
Is the consistent 1.5+ ADA transaction cost a result of this algorithm? My non NFT heavy wallet almost always gives costs below the 0.2 ADA mark. Knowing whether this is intended design or otherwise will help structure personal wallet setup decisions - one to receive and store NFTs and another one to send payments.

If it is not intended design which causes consistently higher transaction costs for the NFT heavy wallet then appreciate if it can be looked into.

**Comment by jonathanknowles** [comment]
> Is the consistent 1.5+ ADA transaction cost a result of this algorithm?

Yes, it is a direct consequence of the particular way in which assets are distributed within your UTxO, and the way in which the coin selection algorithm selects them.

The transaction cost depends on:
- the number and nature of inputs selected by the coin selection algorithm
- the number and nature of the outputs that the user specifies
- the number and nature of the change outputs generated by the coin selection algorithm (this depends entirely on which inputs were randomly selected)

One thing to bear in mind is that coin selection will always need to select more ada from the UTxO than the user actually specifies, in order to pay for the fee.

Generally speaking, when selecting UTxO entries to make a pure ada payment, the wallet will try to choose from pure-ada UTxO entries first. It will only look for mixed entries (containing non-ada assets) if there are no pure ada entries left. 

Suppose that all or most of your ada is locked up in UTxOs that are heavy in non-ada assets (such as NFTs). In such cases, the wallet may have no choice other than to select from these UTxOs when trying to get enough ada to pay for the fee, which may include assets that you didn't specify in your original payment request.

This may in turn increase the fee beyond what would have been possible if there were more pure ada UTxO entries, since all of those non-ada assets need to be paid back to the wallet in the form of change. Change outputs occupy space in the resulting transaction, which has a cost.

One workaround here is to create more pure ada UTxO entries in your wallet. This will give the coin selection algorithm more flexibility to select pure ada UTxO entries when trying to cover the fees required for a transaction.

**Comment by falassiry** [comment]
I appreciate the explanation and clarification. Could this also be directly related to my wallet eventually failing to calculate transaction costs in Daedalus, or taking abnormally long time to calculate them - therefore preventing normal usage? I am seeing 10+ minutes of just waiting for that calculation to happen for 1 single transaction of sending just some ADA from this NFT heavy wallet.

**Comment by jonathanknowles** [comment]
> I am seeing 10+ minutes of just waiting for that calculation to happen for 1 single transaction of sending just some ADA from this NFT heavy wallet.

10 minutes seems very long indeed!

One factor that might be relevant is that the wallet **_currently_** estimates the fee by running the coin selection algorithm **100 times**, and then giving a fee estimate based on a range:

- `estimated_min`: a fee that is less than or equal to 90% of the fees observed in the sample set
- `estimated_max`: the highest fee observed in the sample set 

The reason for generating 100 samples is that coin selection is random. So in other words, the fee you see in Daedalus is just an estimate (but one with high confidence).

In future, we are planning to change the wallet backend, so that instead of running the algorithm 100 times, we'd run it just once. We'd then return the **_actual_** selection to Daedalus, which would then present the **_exact_** fee to the user. If the user is happy with the fee, then Daedalus would supply the same exact selection back to the wallet backend to be transmitted to the network.

**Comment by falassiry** [comment]
As long as my use case is noted out there - I hope this is eventually resolved.

In the meantime, is there any other workaround on my end for this same wallet of mine to become usable? Whether that means adding ADA assets to offset the amount of NFTs or something else, I am willing to consider. Otherwise I will wait for updates to sort this and keep using another wallet for payments until this is fixed.

**Comment by jonathanknowles** [comment]
> In the meantime, is there any other workaround on my end for this same wallet of mine to become usable? Whether that means adding ADA assets to offset the amount of NFTs or something else, I am willing to consider. 

Yes: if you have the ability to add one or more **_pure-ada_** entries to your wallet, then I'd propose giving this a try.

(It should be enough to send a small amount of ada from another wallet to the wallet that's exhibiting the problem.)

On another subject: it strikes me that our current UTxO distribution feature might not be very useful here for debugging, as it only describes the distribution of **_ada_**. It doesn't really tell us much about the distribution of non-ada assets. So it's hard for us to isolate what may be causing the exact problem just by looking at the UTxO distribution (in its current form).

**Comment by jonathanknowles** [comment]
> As long as my use case is noted out there - I hope this is eventually resolved.

@falassiry It is definitely noted. Many thanks for your help in describing this problem. As I mentioned above, there are plans in the works to improve the way we report fees, which will hopefully remove the need to run coin selection 100 times.

Taking 10 minutes to make an estimation is definitely not what we want!

**Comment by falassiry** [comment]
I realize my case is not typical either so I understand and am willing to work around the limitation. Is there any other detail I can offer here to help debug or expose bottlenecks?

**Comment by jonathanknowles** [comment]
> I realize my case is not typical either so I understand and am willing to work around the limitation.

It's true that your case is probably not typical at the moment. Though knowing about your case is extremely valuable to us, as the number of users with NFTs and other non-ada assets will almost certainly increase over time.

> Is there any other detail I can offer here to help debug or expose bottlenecks?

@falassiry I'll confer with others in the team as to the best way to approach this, and we'll get back to you as soon as we can!

**Comment by piotr-iohk** [comment]
Thanks @falassiry. I was trying to reproduce your case on testnet building wallet with 500 unique tokens but with no luck so far. My fee estimation times are in the range of seconds. I'll add more tokens and try to reorganize utxo a bit.

In the meantime if you'd willing to share with us the account public key of the wallet we could debug your case in detail. Sharing account public key would give us "read-only" permissions to your wallet, i.e. we will be able examine your utxo structure in detail and also know what's the wallet balance, but won't be able to run any operations (like transaction, delegation etc.).

Let us know if you'd like to share this information and we'll post detailed step by step how to obtain it and share with us privately via encrypted email. If you're OK sharing this please also let us know the OS you're on, so I'll provide step-by-step specific to your OS.

**Comment by falassiry** [comment]
I can share it - I can access the public key and just need details on how you'd like me to send it.

**Comment by jonathanknowles** [comment]
> I can share it - I can access the public key and just need details on how you'd like me to send it.

@falassiry that's great news.

Would you be able to send it to one of the following addresses:

- `jonathan.knowles` at `iohk.io` (GPG public key available [here](https://keyserver.ubuntu.com/pks/lookup?search=jonathan.knowles%40iohk.io&fingerprint=on&op=index)).
- `piotr.stachyra` at `iohk.io` (GPG public key available [here](https://keyserver.ubuntu.com/pks/lookup?search=piotr.stachyra%40iohk.io&fingerprint=on&op=index)).

Thanks in advance!

**Comment by ceno666** [comment]
Greetings and thanks to @falassiry for redirecting me here.

I have the exact same problem, fee calculation takes like forever.
My wallet cointans 316 NFT tokens.

33 UTXOs between 1-10 ADA
1 UTXO between 100-1k ADA
1 UTXO between 1k-10k ADA

**Comment by piotr-iohk** [comment]
@ceno666 @falassiry thanks for reporting! We managed to reproduce your behavior with a testnet wallet and have this issue in our backlog now.

If you'd willing to share your public account key of the wallet that would be helpful too to get more insight into the issue -> https://github.com/input-output-hk/cardano-wallet/issues/2622#issuecomment-828256986

For the record we'd need output from this ep -> https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/postAccountKey.

**Comment by ghost** [comment]
Hi there,
Currently we mint a thousands NFT with scenario as below:

We minted NFTs by ~ 24 transactions, each transaction contain 100 NFTs
After that, we sent 50 NFTs ( = 50 transactions, respectively) to others. And the fee arround 1.9 ADA for total
But for now, we try to send NFT, the fee is higher (~ 6ADA ) and unsuccessful.

![image](https://user-images.githubusercontent.com/67568662/119643738-50f2a700-be46-11eb-9bf8-8060d5011bcb.png)

I assumed that cardano blockchain network merged all UTXOs to one. And now it is too long (because we have thousand of NFTs) so cardano got stuck when calculate tx-in and tx-out (the time out got from server, I think)

Thanks!

**Comment by SmaugPool** [comment]
My wallet is stuck too with 7 UTXOs and 209 tokens, using a Ledger Nano S.

I can provide more information if needed.

**Comment by piotr-iohk** [comment]
Fix for this issue landed already in master (https://github.com/input-output-hk/cardano-wallet/pull/2676). It should improve fee estimation in case of NFT-packed wallets and thus hopefully unblock them. It will be available in the next cardano-wallet release.

In the meantime, if you'd like, you may check if current cardano-wallet master handles your wallet better. :+1:

**Comment by SmaugPool** [comment]
> Fix for this issue landed already in master (#2676). It should improve fee estimation in case of NFT-packed wallets and thus hopefully unblock them. It will be available in the next cardano-wallet release.
> 
> In the meantime, if you'd like, you may check if current cardano-wallet master handles your wallet better. +1

That's great news! Thank you.

**Comment by Onotoko** [comment]
> next cardano-wallet release

That's great. Thank you!

**Comment by ghost** [comment]
> Fix for this issue landed already in master (#2676). It should improve fee estimation in case of NFT-packed wallets and thus hopefully unblock them. It will be available in the next cardano-wallet release.
> 
> In the meantime, if you'd like, you may check if current cardano-wallet master handles your wallet better. +1

That's great. Thank you!
And when is next release @piotr-iohk ?

**Comment by matiwinnetou** [comment]
Check out if today's 4.1.0 Daedalus contains this fix...

**Comment by nikolaglumac** [comment]
I am sorry to disappoint you but this fix was merged after the release of cardano-wallet [`v2021-05-26`](https://github.com/input-output-hk/cardano-wallet/tree/v2021-05-26) which is the version used in Daedalus 4.1.0...

**Comment by ghost** [comment]
@nikolaglumac
We hope in the next version of Daedalus soon

**Comment by nikolaglumac** [comment]
I am pretty sure we will have it in the next Daedalus version. 
Thanks for the patience!

**Comment by ghost** [comment]
Thank you very much @nikolaglumac

**Comment by ghost** [comment]
Hi @piotr-iohk.
Today I tried to pull newest code of cardano-wallet 
```
wget https://raw.githubusercontent.com/input-output-hk/cardano-wallet/master/docker-compose.yml
NETWORK=maiinet docker-compose up
```

And try to run the API for calculating fee: http://localhost:8090/v2/wallets/{walletID}/payment-fees   but it seems the issue has not fixed on latest merged yet because I have to wait long time and no respond from that API. 

Otherwise, If I use the API: http://localhost:8090/v2/wallets/{walletID}/transactions
I got an error

```
{
    "code": "created_invalid_transaction",
    "message": "That's embarrassing. It looks like I've created an invalid transaction that could not be parsed by the node. Here's an error message that may help with debugging: HardForkApplyTxErrFromEra S (S (S (Z (WrapApplyTxErr {unwrapApplyTxErr = ApplyTxError [LedgerFailure (UtxowFailure (UtxoFailure (MaxTxSizeUTxO 32450 16384)))]}))))"
}
```

Any suggestion?

Thank you!

**Comment by piotr-iohk** [comment]
Hello @oanhsaitec, please note that the fix is not included in the latest wallet release (2021-05-26). If you'd like to try out the master version of the wallet with docker-complose you have to modify docker-compose.yml (https://github.com/input-output-hk/cardano-wallet/blob/master/docker-compose.yml#L21) replacing `2021.5.26` with `dev-master` before:
```
NETWORK=mainnet docker-compose up
```

**Comment by ghost** [comment]
Thank you @piotr-iohk,
When I changed to the dev-master, first transaction I created successfully, the second on I got 
```
{
    "status": "pending",
    "withdrawals": [],
    "amount": {
        "quantity": 4080793,
        "unit": "lovelace"
    },
    "inputs": [
        {
            "amount": {
                "quantity": 24502323,
                "unit": "lovelace"
            },
            ...
```

but actually, I check on pool.pm has nothing sent to it

Any clues?

p/s: it seems I have to wait a couple of minutes before send the next transaction.
Also, I checked at the local log and got

```
cardano-wallet_1  | [cardano-wallet.network:Info:181] [2021-06-07 10:55:49.90 UTC] Recv (ServerAgency TokBusy,MsgAcceptTx)

```

**Comment by piotr-iohk** [comment]
@oanhsaitec please note that your transaction was still in pending state:
```
"status": "pending",
```
i.e. submitted to the local node but not yet propagated. You need to wait until transaction status changes to `in_ledger` to be able to observe it on the blockchain.

**Comment by ghost** [comment]
@piotr-iohk,
Yes, you are right. it needs time to be on-chain then I should add TTL around 1 min.

Thank you so much for your support!

**Comment by piotr-iohk** [comment]
Fix for this issue has been delivered in cardano-wallet v2021-06-11 and Daedalus 4.2.0.
