### ISSUE TITLE
Weeder: Command exited with code -9

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#2695]
# Context
 
# Test Case

Weeder check

# Failure / Counter-example

```
--- Weeder
weeder 
error: Command exited with code -9!
Continuing...
./buildkite-script-15be0fbf-9d48-4997-b874-643c35bebbf3: line 5: 30308 Killed                  ./sr/bin/rebuild --build-dir=$BUILD_DIR --cache-dir=$CACHE_DIR
```

# Resolution 

---

# QA

**Comment by rvl** [comment]
On Linux, if a process exits with -9, it's because it's been killed with SIGKILL.

Normally builds or processes are stopped with SIGTERM or SIGINT.

So I believe this build failure is probably due to the Linux OOM killer running on the Buildkite build agent.

It may have been another project's build running at the same time which used all the memory and caused our build to be zapped.

This would hopefully be a pretty rare situation.

@Anviking If you provide a link to the buildkite job, we examine the grafana host monitoring charts at the time of the build, and perhaps see the cause.

**Comment by Anviking** [comment]
> If you provide a link to the buildkite job, we examine the grafana host monitoring charts at the time of the build, and perhaps see the cause.

@rvl FYI they are linked indirectly through github:

<img width="890" alt="Skärmavbild 2021-06-10 kl  14 22 06" src="https://user-images.githubusercontent.com/304423/121524095-3d733e80-c9f7-11eb-9534-8e8edb3029d3.png">

But e.g. https://buildkite.com/input-output-hk/cardano-wallet/builds/15044

**Comment by rvl** [comment]
OK I see. The monitoring shows something gobbled all the memory at the time the build failed:

![grafana-packet-ipxe-2](https://user-images.githubusercontent.com/1019641/121625040-09ab1e00-cab6-11eb-80b7-e5dc6eb1e1e9.png)

**Comment by rvl** [comment]
I wonder if it's a problem with weeder itself. Because after looking at the logs for packet-ipxe-2, the only jobs running around the same time were:
- https://buildkite.com/input-output-hk/cardano-wallet/builds/15044#15be0fbf-9d48-4997-b874-643c35bebbf3 (weeder)
- https://buildkite.com/input-output-hk/cardano-wallet/builds/15045#828bcede-9de4-4eae-87b3-aad77d844eb8 (docker)
- https://buildkite.com/input-output-hk/cardano-wallet/builds/15045#2422a53a-c9fd-4503-9ebb-3728a8268eaa (lentil)

**Comment by Anviking** [comment]
> OK I see. The monitoring shows something gobbled all the memory at the time the build failed:

😮 nice finding!

> I wonder if it's a problem with weeder itself.

✔️ 🤔

**Comment by rvl** [comment]
Happened again in https://buildkite.com/input-output-hk/cardano-wallet/builds/15563#d800ef36-7911-4a15-aced-2e28621653ce/10267-10269. The weeder step was running for 27 minutes before it was killed.

**Comment by rvl** [comment]
After the weeder config fixes, I found this error on Buildkite:
```
incompatible hie file: /build/cardano-wallet/lib/text-class/.stack-work/dist/x86_64-linux/Cabal-3.2.1.0/build/Test/Text/Roundtrip.hie
    expected .hie file version 8104 but got 8105
    weeder must be built with the same GHC version as the project it is used on
```
That is due to loading a cached `.stack-work` built with a previous compiler version.

Perhaps the weeder problem is due to corrupted `.hie` files or something like that?
