### ISSUE TITLE
docker-compose not running properly on OSX `failed to create symbolic link '/cardano-wallet/data: File exists'

### ISSUE THREAD

**Issue by stephenhuh** [cardano-foundation/cardano-wallet#2864]
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [X] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

n/a

### Platform

macOS Big Sur

### Installation method

IOHK Docker image

### Network configuration

testnet/mainnet

## Steps to Reproduce

1. `wget https://raw.githubusercontent.com/input-output-hk/cardano-wallet/master/docker-compose.yml`
2. `NETWORK=testnet docker-compose up`
3.  > cardano-wallet_1 exited with code 1

...

### Expected behavior

The expected behavior is that the cardano-wallet docker image successfully boots.

### Actual behavior

When I run `docker logs -f <docker id>` 
I receive the following logs:
```
Invalid argument `bash'

Usage: cardano-wallet COMMAND
  Cardano Wallet Command-Line Interface (CLI)
Invalid argument `bash'

Usage: cardano-wallet COMMAND
  Cardano Wallet Command-Line Interface (CLI)
ln: failed to create symbolic link '/cardano-wallet/data': File exists
ln: failed to create symbolic link '/cardano-wallet/data': File exists
ln: failed to create symbolic link '/cardano-wallet/data': File exists
ln: failed to create symbolic link '/cardano-wallet/data': File exists
ln: failed to create symbolic link '/cardano-wallet/data': File exists
.
.
.
```

**Comment by piotr-iohk** [comment]
Thanks for reporting. Jira issue for tracking: https://input-output.atlassian.net/browse/ADP-1115.

**Comment by piotr-iohk** [comment]
I was trying to reproduce the issue on MacOS (MacOS 10.15 and MacOS 11) on GH actions, but it seems work fine there. Both cardano-node and cardano-wallet spin up with no issue from docker-compose there -> https://github.com/input-output-hk/cardano-wallet/actions/runs/1233307144.

**Comment by raveli** [comment]
I'm able to reproduce this with the exact steps described by op. Tested on Windows 11 WSL2 (Ubuntu 20.04). Docker version 20.10.8, build 3967b7d.

**Comment by piotr-iohk** [comment]
Few questions:
 - is is a first launch of docker-compose on this machine or was it working fine before? (e.g. with previous versions of wallet and node)
 - does cleaning up docker possibly help? e.g.:
```
docker rm -f $(docker ps -a -q)
docker volume rm -f $(docker volume ls -q)
docker image rm -f $(docker image ls -q)
```

**Comment by stephenhuh** [comment]
@piotr-iohk

• this is a first launch 
• just ran the docker clean commands and still running into the issue

**Comment by stephenhuh** [comment]
the cardano node itself seems to be functioning well, just the wallet image is giving that error

**Comment by npattman** [comment]
I've got this issue too on Windows 10 Enterprise with Docker. I can get the node and wallet running if I download and run the release assets directly from https://github.com/input-output-hk/cardano-wallet/releases
i.e. 
`cardano-wallet serve --node-socket \\.\pipe\cardano-node-testnet --testnet testnet-byron-genesis.json --database /wallet-db --listen-address 0.0.0.0`
and
`cardano-node run --config testnet-config.json --database-path /db/ --socket-path \\.\pipe\cardano-node-testnet --host-addr 127.0.0.1 --port 1337 --topology testnet-topology.json`

If doing that I need to run the wallet as admin (presumably because of the named pipe access). No joy with Docker (current latest), have nuked images etc, etc. Strange thing is that my copy of docker compose hasn't changed and this was working a few days ago, it's as if the remote wallet image (2021.9.9) has become corrupt/invalid. Am working around it in the meantime by running the release artefacts manually as per the above. Hope this helps someone.

**Comment by stephenhuh** [comment]
i worked around this by building the cardano-wallet from source using stack. this method is definitely way more involved and also dont get the benefits of docker. but, if cardano-wallet is needed immediately it does work.

**Comment by glneto** [comment]
are you using `docker compose up` or `docker-compose up`? it may seem stupid but I was having this issue with `docker compose up` and using `docker-compose up` seems to have fixed it

**Comment by npattman** [comment]
Hey Geraldo, I have just tried

docker-compose up

and that appears to work… so I think you’re correct… that’s awesome, many thanks for your help :)

**Comment by stephenhuh** [comment]
@glneto no that doesn't seem to be it. i believe i was running `docker-compose up` and retried just to confirm.

**Comment by abcirta** [comment]
Hi,
any update ?

**Comment by rvl** [comment]
Hi there,

1. Do you have any old images listed in `docker ps --all`?
2. Are there any volumes mounted at `/cardano-wallet`, anything like that?

**Comment by gunar6** [comment]
Hi, 
I'm getting the following error while running `NETWORK=testnet docker-compose up`
`ERROR: Named volume "node-testnet-db:/data:rw" is used in service "cardano-node" but no declaration was found in the volumes section.`

Also when I run `NETWORK=testnet docker compose up`
I'm getting this `service "cardano-wallet" refers to undefined volume wallet-testnet-db: invalid compose project`

It seems the issue is `node-testnet-db` not defined here:

https://raw.githubusercontent.com/input-output-hk/cardano-wallet/master/docker-compose.yml
```
volumes:
  node-mainnet-db:
  wallet-mainnet-db:
  node-preprod-db:
  wallet-preprod-db:
  node-preview-db:
  wallet-preview-db:
  node-ipc:
  node-config:
```

**Comment by piotr-iohk** [comment]
Testnet is legacy environment which will be decommissioned soon therefore we've removed configuration for that environment alltogether. Instead there are two new test environments: [preview](https://book.world.dev.cardano.org/environments.html#preview-testnet) and [preprod](https://book.world.dev.cardano.org/environments.html#pre-production-testnet). You should be able to access both:
```
NETWORK=preview docker-compose up
```
or
```
NETWORK=preprod docker-compose up
```

**Comment by SeungheonOh** [comment]
I'm getting same symlink error on NixOS system. 

```
316cf322b71a   inputoutput/cardano-wallet:latest                     "start-cardano-walle…"   17 minutes ago   Exited (1) 12 minutes ago                                                store_cardano-wallet_1
9f875d3a553d   inputoutput/cardano-node:1.35.4                       "entrypoint run --co…"   15 hours ago     Exited (1) 5 seconds ago                                                 store_cardano-node_1
```

```
Client:
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        v20.10.17
 Built:             Thu Jan  1 00:00:00 1970
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       v20.10.17
  Built:            Tue Jan  1 00:00:00 1980
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.6
  GitCommit:        v1.6.6
 runc:
  Version:          1.1.2
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:    
```

Weirdly, this doesn't fail on the first run. It starts to fail after quitting the first session and running again.
