### ISSUE TITLE
Flaky test: `/CLI Specifications/SHELLEY_CLI_TRANSACTIONS/TRANS_DELETE_01`

### ISSUE THREAD

**Issue by jonathanknowles** [cardano-foundation/cardano-wallet#2886]
### Please ensure:

- [X] This is actually a flaky test already present in the code and not caused by your PR.

### Context

https://github.com/input-output-hk/cardano-wallet/pull/2885#issuecomment-916761510

### Job name

https://buildkite.com/input-output-hk/cardano-wallet/builds/16551#ed15249e-3da0-4700-b514-80607214777a

### Test case name(s)

/CLI Specifications/SHELLEY_CLI_TRANSACTIONS/TRANS_DELETE_01

### Error message

```shell
src/Test/Integration/Scenario/CLI/Shelley/Transactions.hs:781:9: 
  1) CLI Specifications, SHELLEY_CLI_TRANSACTIONS, TRANS_DELETE_01 - Cannot forget pending transaction when not pending anymore via CLI
       "Ok.\n" does not contain "The transaction with id: d9d176cbf97fe8dd08956b3f2ab276d7e32be0aa2dafa8040d126f51af74077b cannot be forgotten as it is already in the ledger."
 
  To rerun use: --match "/CLI Specifications/SHELLEY_CLI_TRANSACTIONS/TRANS_DELETE_01 - Cannot forget pending transaction when not pending anymore via CLI/"
 
Randomized with seed 1455226691
```

### Build link

https://buildkite.com/input-output-hk/cardano-wallet/builds/16551#ed15249e-3da0-4700-b514-80607214777a

**Comment by Anviking** [comment]
Seems there was a rollback:

https://github.com/input-output-hk/cardano-wallet/blob/master/lib/wallet/integration/src/Test/Integration/Scenario/CLI/Shelley/Transactions.hs#L839-L841

We are using the retrying `it`, so I think this was a specific instance of a rare but general problem. I think we can close.

**Comment by paolino** [comment]
Recurrence observed on 2026-07-29 in PR #5345 CI attempt 1:

- Run: https://github.com/cardano-foundation/cardano-wallet/actions/runs/30431737621
- Job: `Conway Integration Tests`
- Test: `TRANS_DELETE_01 - Cannot forget pending transaction when not pending anymore via CLI`
- Failure: the delete command returned `"Ok.\n"` instead of the expected `"The transaction with id: … cannot be forgotten as it is already in the ledger."`
- The same race occurred on the test's automatic retry, so attempt 1 ended with 1 failure.

This is the exact failure signature tracked here. PR #5345 changes only its gate and specification documents, and the Conway integration job on its base commit was green, so this recurrence is unrelated to that PR's diff.

Leaving the issue closed for this recurrence; reopen on the next recurrence.

---

🤖 Claude opus 5 agent
