### ISSUE TITLE
Doc example for create/restore wallet doesn't work out of the box

### ISSUE THREAD

**Issue by v0d1ch** [cardano-foundation/cardano-wallet#2907]
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [X] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

0d21f8b9e4d9b903676cea035a6bfb274bf661ea

### Platform

NixOS 20.09

### Installation method

IOHK Docker image

### Network configuration

testnet

### Context

The example in the docs for creating new wallet using mnemonic sentence fails. I get:

```
Invalid entropy checksum: please double-check the last word of your mnemonic sentence.
```
The example for using pub key works just fine.

## Steps to Reproduce

1. Clone the cardano-wallet repo
2. Run 
```
wget https://raw.githubusercontent.com/input-output-hk/cardano-wallet/master/docker-compose.yml
NETWORK=testnet docker-compose up
```
which gets the wallet node running correctly

3. I used postman to hit `http://localhost:8090/v2/wallets` with post request using body provided in the documentation:
```
{
  "name": "Alan's Wallet",
  "mnemonic_sentence": [
    "squirrel",
    "material",
    "silly",
    "twice",
    "direct",
    "slush",
    "pistol",
    "razor",
    "become",
    "junk",
    "kingdom",
    "flee",
    "squirrel",
    "silly",
    "twice"
  ],
  "mnemonic_second_factor": [
    "squirrel",
    "material",
    "silly",
    "twice",
    "direct",
    "slush",
    "pistol",
    "razor",
    "become"
  ],
  "passphrase": "Secure Passphrase",
  "address_pool_gap": 20
}
```

### Expected behavior

I should get the expected response as per documentation `https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/postWallet`

### Actual behavior
I get:
`Invalid entropy checksum: please double-check the last word of your mnemonic sentence.`

**Comment by piotr-iohk** [comment]
Hello, thanks. These mnemonic phrases examples are invalid on purpose, because in the past we had some users restoring  wallets from these doc mnemonics and using them as their personal wallets.

To generate valid mnemonic phrase you can use:
 - cardano-wallet CLI (`$ cardano-wallet recovery-phrase generate`)
 - external library implementing [BIP39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#Reference_Implementation)
 - external service like https://iancoleman.io/bip39/
