### ISSUE TITLE
feature to request additional addresses for a wallet

### ISSUE THREAD

**Issue by benapetr** [cardano-foundation/cardano-wallet#2921]
### The problem that you wish to solve

Right now from perspective of someone who implements a "merchandize" system such as e-shop based on cardano - you need to be able to distinguish customers from each other. In ideal situation you assign each customer unique address to which they should send ADA in order to recognize which customer sent ADA (in some cases you may need to have unique address for each order).

cardano-wallet generates only about 20 addresses per wallet. It would be nice if there was some method to generate N additional addresses if current pool is depleted.

### Description

Create method (or parameter for addresses call) to generate additional addresses for a wallet

**Comment by HeinrichApfelmus** [comment]
Thanks for the feedback!

Note that if the wallet detects a payment to or from an address listed in the https://localhost:8090/v2/wallets/{walletId}/addresses endpoint, it will automatically discover new addresses so that ~ 20 unused addresses are available. Unfortunately, that's not quite what you are looking for, in that you probably have many more addresses for which you expect payments.

Unfortunately, increasing this so-called _address gap_ (default 20) makes restoration from a seed mnemonic more difficult -- if you have, say, 1000 consecutive unused addresses (users that did not send funds), the wallet may not be able to discover some payments if it is only looking ahead 20 addresses. This is a technical limitation of the industry standard BIP-44, on which the CIP-1852 standard is based upon.

I'm currently working on making larger address gaps more practical, and I'm looking into alternative standards. It will take a while, though.

In the meantime, possible workarounds include:

* Using transaction metadata
* Using the address derivation method to generic addresses and combine this with cardano-db-sync in order to discover payments to these addresses.

**Comment by benapetr** [comment]
well, the thing is I don't even have these extra addresses, but I would like to have them, basically right now I would be only able to handle first 20 customers, or actually, first 20 orders, for other orders I would have to return error "address pool depleted" or something like that.

Or I would need to create huge amount of wallets, each to get 20 addresses, but that also would be very impractical. I think this is a blocker for everyone who wants to create an online store that uses cardano for payments.

I am also wondering how exchanges overcame this problem, when you want to deposit ADA to exchange, every user gets a unique address to deposit to, so they must have millions of addresses per wallet? So it is probably doable.

**Comment by benapetr** [comment]
I can't even solve this by knowing senders address, even if I told customers to send to adress addr_XXXXX and fill their address before they start transaction - they will never know from which address is ADA going to be sent, due to this bug - https://github.com/input-output-hk/cardano-wallet/issues/2614 cardano-wallet randomly redistributed ADA across the wallet, and automatically picks which addresses it takes the UTXOs from, and users don't have any way to affect this.

**Comment by paweljakubas** [comment]
hi @benapetr  One way to create addresses (having the same mnemonic, account index=0 - for now only this is supported and arbitrary address index) is to use https://github.com/input-output-hk/cardano-addresses/

1. So let's assume we have mnemonics:
```
$ cat mnemonics.txt 
whisper control diary solid cattle salmon whale slender spread ice shock solve panel caution upon scatter broken tonight
```
2. Create extended root private key:
```
$ cardano-address key from-recovery-phrase Shelley < mnemonics.txt > root.xsk
$ cat root.xsk
root_xsk1kra0jaflzzgtwu5mxl3qsv0gga05fyd3g0yslf3q0kgsq7ctep2wq9yjg4sgq2rwnpcuk2dw8czw9qde5f9ank5vr080fn4z9vzk8zdkvgj7qt6lmlxyn6hm2ne0ymg2srpxfu6cqxxzz75wh93u6klenqxuet7a
```
3. Create stake verification key (this would be needed if you want to stake, so create base address, rather than enterprise address)
```
$ cardano-address key child 1852H/1815H/0H/2/0 < root.xsk | cardano-address key public --with-chain-code > stake.xvk
$ cat stake.xvk 
stake_xvk14tq9nymn3m76f3q3c99aru5az6dk6az02h6d5flj6g8ghw5qvte79n5w2t5m2ezplw2zgrry8nm86dlw7rdlv46qt8ltp30jpd4malgt7zj8j
```
(please notice that 0H account index was used, role=2 and stake index=0 - this should not change)
4. Now create payment verification key:
```
$ cardano-address key child 1852H/1815H/0H/0/0 < root.xsk | cardano-address key public --with-chain-code > addr0.xvk
$ cat addr0.xvk 
addr_xvk17sy8yc35xvdc8wg6ssy33yhjr34qtkhdk52p7m2y5qpjxrxhzf53r4scun52lwd0uf6rtke5hy00ejh7sqa9aufa2nlvzxtptycp0lcu4lkx8
$ cardano-address key child 1852H/1815H/0H/0/1000 < root.xsk | cardano-address key public --with-chain-code > addr1000.xvk
$ cat addr1000.xvk 
addr_xvk1u4whatpud5wrkw89vhfx2qcnvw9tjl4q4k246ln42zzht9369aevhxvus9tq4uf6jp8h7vcwhtvsz06lrq06dx70vmln83jaqfekussxsmy50
```
(we used here 0H account public key, role=0 and (ix=0 first example, x=1000 second example) ). This is how you can create many payment verification keys! 
5a (for enterprise address - not staking) for testnet
```
$ cardano-address address payment --network-tag testnet < addr0.xvk > enterprise0.addr
$ cat enterprise0.addr 
addr_test1vqjl24fqvgdfsd8x7tc5trwpyafq3qg78dp3w3ugct69eaqdkedcf
$ cardano-address address payment --network-tag testnet < addr1000.xvk > enterprise1000.addr
$ cat enterprise1000.addr 
addr_test1vp5unv4h7f6743hgzqsejhsht3jj9yg6a736w5ljeh2khkcfazhvf
```
5b (base addresses staking) for testnet
```
$ cardano-address address delegation $(cat stake.xvk) < enterprise0.addr > base0.addr
$ cat base0.addr 
addr_test1qqjl24fqvgdfsd8x7tc5trwpyafq3qg78dp3w3ugct69eazqmr34pgfevux4mslq44avqpjxm9hw2ymyquy6zuy0npmq4p4uf6
$ cardano-address address delegation $(cat stake.xvk) < enterprise1000.addr > base1000.addr
$ cat base1000.addr 
addr_test1qp5unv4h7f6743hgzqsejhsht3jj9yg6a736w5ljeh2khk6qmr34pgfevux4mslq44avqpjxm9hw2ymyquy6zuy0npmqelmpxa
```

**Comment by piotr-iohk** [comment]
>Or I would need to create huge amount of wallets, each to get 20 addresses, but that also would be very impractical. I think this is a blocker for everyone who wants to create an online store that uses cardano for payments.

Actually Shelley wallets API allows creating wallets with larger address pool gap (up to 100k addresses), however it comes with some wallet performance cost (see: https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/postWallet). 

Another option at the moment can be Byron wallets (see: https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/postByronWallet). Byron wallets follow random address scheme so it is possible to create new address on the wallet (see: https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/createAddress), or even import some addresses (see: https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/importAddresses) which were created outside (e.g. using cardano-address).

**Comment by HeinrichApfelmus** [comment]
benapetr :
> I am also wondering how exchanges overcame this problem, when you want to deposit ADA to exchange, every user gets a unique address to deposit to, so they must have millions of addresses per wallet? So it is probably doable.

piotr-iohk:
> Another option at the moment can be Byron wallets

Some exchanges do use Byron wallets, I suppose for this very reason.

**Comment by HeinrichApfelmus** [comment]
@benapetr

> I can't even solve this by knowing senders address, even if I told customers to send to adress addr_XXXXX and fill their address before they start transaction

Instead of using addresses to disambiguate users, you could also try to use transaction metadata to disambiguate them. This is very similar to the "transfer note" or "intended purpose" for SEPA bank transfers, where retail shops often instruct buyers to include their invoice number. The drawback is that this is extra information which has to be provided by the user.

**Comment by benapetr** [comment]
@HeinrichApfelmus

> @benapetr
> 
> > I can't even solve this by knowing senders address, even if I told customers to send to adress addr_XXXXX and fill their address before they start transaction
> 
> Instead of using addresses to disambiguate users, you could also try to use transaction metadata to disambiguate them. This is very similar to the "transfer note" or "intended purpose" for SEPA bank transfers, where retail shops often instruct buyers to include their invoice number. The drawback is that this is extra information which has to be provided by the user.

this is interesting idea, but is it supported by mainstream wallets? so in theory:

there would 1 central address to which all users would send ADA, each merchant order would be distinct by ID which user would need to provide as transaction metadata. If metadata and amount matches - order is confirmed, otherwise user is asked to correct the amount. For orders that don't match (or missing metadata) user should be refunded back - which is the tricky part - because:

1 - we need to calculate the max_fee and deduct it from returned amount, so that the customer who made the mistake pays the transaction fee and not merchant, otherwise malicious users could abuse this by repeatedly sending invalid transactions
2 - there may not only be ADA as part of this transaction, if someone sends native tokens, they should be also sent back
3 - there could be multiple source addresses, should the ADA be returned to all of them? What if after deduction of max_fee some of the UTXOs would be less than 1ADA and thus impossible to be sent?
4 - what is some part of transaction is made from reward address? where should it be sent back?

To be honest - "refund" or some sort of "rollback" operation seems to me so complex that it should probably be implemented in cardano-wallet as well. If this model that is utilizing transaction metadata is supposed to be widespread, then it would make sense to support this flow in basic tools used by merchants, so that they don't need to keep implementing this same workflow on their own.

**Comment by HeinrichApfelmus** [comment]
> For orders that don't match (or missing metadata) user should be refunded back […]
>
> To be honest - "refund" or some sort of "rollback" operation seems to me so complex that it should probably be implemented in cardano-wallet as well. If this model that is utilizing transaction metadata is supposed to be widespread, then it would make sense to support this flow in basic tools used by merchants, so that they don't need to keep implementing this same workflow on their own.

Thanks for bringing this up, it seems to me that "refunding" is indeed a useful feature. In fact, it seems to be useful even for the original problem of matching customers to addresses: In the worst case, customers may send money to the wrong address and then the funds are gone. When using metadata, at least the shop now owns those funds and can refund them in principle. (Granted, transaction metadata is more likely to go wrong than addresses, because this problem gets much more attention for addresses. But still).

Anyway, it appears that consumer-facing wallets do not support metadata at the time of this writing.

**Comment by gituser** [comment]
Any update on this?

Why not make an API function of extending the address pool manually? 

Sometimes it is needed when you have e.g. 0 incoming transactions and your address pool is exhausted.

**Comment by HeinrichApfelmus** [comment]
Compliance with the industry standard BIP-44 / CIP-1852 does not allow us to change the `address_pool_gap`. 😞 

> Why not make an API function of extending the address pool manually?

The address pool gap cannot be changed dynamically. As a workaround, you can specify a value of `address_pool_gap` when restoring a wallet, though.

> Sometimes it is needed when you have e.g. 0 incoming transactions and your address pool is exhausted.

Could you elaborate? When you make any transaction, the address pool should enlarge automatically.

The "e-shop" scenario was never meant to be supported by BIP-44 / CIP-1852, at least not in this form.

**Comment by gituser** [comment]
@HeinrichApfelmus 
>Could you elaborate? When you make any transaction, the address pool should enlarge automatically.

If you accept Cardano (ADA) payments only and do not do any withdrawals the pool might be quickly exhausted.

**Comment by teddyjfpender** [comment]
@benapetr I'd really like to know a little more about this use case you're describing for `cardano-wallet`. Can you dive into the scenario a little more, perhaps touch on some things like: comparable existing products/payment services (decentralised/centralised), benefits of one-user-one-address, and extensions of this model (e.g. analytics, what you'd like to achieve if such a feature was created)? 

Grateful if you could share any thoughts with us :-)

**Comment by bogerv** [comment]
> @benapetr I'd really like to know a little more about this use case you're describing for `cardano-wallet`. Can you dive into the scenario a little more, perhaps touch on some things like: comparable existing products/payment services (decentralised/centralised), benefits of one-user-one-address, and extensions of this model (e.g. analytics, what you'd like to achieve if such a feature was created)?
> 
> Grateful if you could share any thoughts with us :-)

Example of exchanges like Binance
Each user needs to have its own unique address identification, in order to know which user has actually deposit on the chain.
However, most exchanges currently do not support additional meta data for withdrawal ADA.

**Comment by benapetr** [comment]
yes exactly this - imagine you need to create an endpoint where 10 000 different users can deposit some tokens or ADA and you differentiate each of them. Easiest would be to generate 10 000 different addresses, assign one to each user, and track their balance by adding what is sent to these addresses.

of course it's necessary to separately track the balances in separate database, you can't trust on-chain data, because cardano-wallet is randomly reshuffling UTXO between addresses randomly, per https://github.com/input-output-hk/cardano-wallet/issues/2614

**Comment by HeinrichApfelmus** [comment]
The Deposit Wallet is in progress to address this and similar use cases.

**Comment by gituser** [comment]
> The Deposit Wallet is in progress to address this and similar use cases.

@HeinrichApfelmus 
Did you mean this pull request https://github.com/cardano-foundation/cardano-wallet/pull/4837 ?

What about address pool exhaustion? Will it be fixed in this feature?

Thanks

**Comment by HeinrichApfelmus** [comment]
> Did you mean this pull request

It's a new wallet that we are currently working on and going to include in future releases of `cardano-wallet`. If you want to get an overview of the pull request relevant to this, have a look at the label https://github.com/cardano-foundation/cardano-wallet/labels/Deposit .

We hope to make it easier to follow our work soon.

**Comment by abailly** [comment]
@gituser Would you be available for a chat in the near future? We are looking for feedback from users to ensure this new wallet will fit the needs and alleviate some pain points of the existing cardano-wallet.

**Comment by gituser** [comment]
@abailly 
> @gituser Would you be available for a chat in the near future? We are looking for feedback from users to ensure this new wallet will fit the needs and alleviate some pain points of the existing cardano-wallet.

I'm available in this issue or feel free to create a discussion.
For our company the address exhaustion is a major blocker to enable Cardano support.

**Comment by abailly** [comment]
> 
> I'm available in this issue or feel free to create a discussion. 
> For our company the address exhaustion is a major blocker to enable Cardano support.

I was thinking of having a chat using google meet, in order to better understand your use case and whether or not the features we are working on for the deposit wallet would love the issues you're currently having with c-w.

**Comment by gituser** [comment]
Hello!

@abailly @HeinrichApfelmus would you mind updating the status on this issue and/or re-opening it?

Also regarding `deposit` wallet is it a new wallet implementation? Will be there a different codebase?

Is there any way to try it and how?

**Comment by abailly** [comment]
@gituser The code for the deposit Wallet lives in https://github.com/cardano-foundation/cardano-deposit-wallet and currently is at the prototype stage. There's a draft website available with some documentation available at https://hal:cf2025@deposit.pankzsoft.net/ with some explanations and a recorded demo explaining what it does. 

As you may have noticed, the Cardano-wallet repository is in the maintenance mode so we don't have any plans to implement new features on it and we are not actively working on the deposit wallet either. As I suggested 6 months ago, the best approach would be to have a more detailed explanation of your particular use case in order to explore options.

I can offer you to join our [discord](https://discord.gg/FeBWXxHn) to chat, or reach out [Cardano Foundation on Twitter](https://x.com/Cardano_CF) for advices as the Cardano Foundation has people dedicated to help organisations adopt Cardano.

**Comment by gituser** [comment]
@abailly 
> As I suggested 6 months ago, the best approach would be to have a more detailed explanation of your particular use case in order to explore options.

The use case is very simple:

* we generate new addresses using cardano-wallet API for new invoices
* at some point address exhaustion is happening and we no longer can create new addresses
* the workaround to create a wallet with 100K limit doesn't look like a proper solution because as it was mentioned wallet becomes laggy and also it's possible that there will be 100K invoices without any withdrawal and exhaustion might happen again

Implementing this feature will benefit not only me but also others in this issue thread.

>As you may have noticed, the Cardano-wallet repository is in the maintenance mode so we don't have any plans to implement new features on it and we are not actively working on the deposit wallet either. 

That's sad news, does it mean at some point cardano-wallet becomes abandoned project?

>I can offer you to join our [discord](https://discord.gg/FeBWXxHn) to chat, or reach out [Cardano Foundation on Twitter](https://x.com/Cardano_CF) for advices as the Cardano Foundation has people dedicated to help organisations adopt Cardano.

Your discord requires a phone number attached to the discord's account which I don't have.

**Comment by abailly** [comment]
> Implementing this feature will benefit not only me but also others in this issue thread.

Sure, but there might exist other approaches to your problem hence why I am offering to discuss in more details.

> That's sad news, does it mean at some point cardano-wallet becomes abandoned project?

We are committed to maintain it so no, it's not abandoned and we'll keep upgrading it to new node versions (albeit slowly). Furthermore, it's open-source software so anyone can fork it.

> Your discord requires a phone number attached to the discord's account which I don't have.

If you email to hal@cardanofoundation.org then I can forward your email to people who might reach out to help you.

**Comment by gituser** [comment]
> If you email to [hal@cardanofoundation.org](mailto:hal@cardanofoundation.org) then I can forward your email to people who might reach out to help you.

I just did, thank you!
