### ISSUE TITLE
Implement `estimateFee` endpoint & `transaction fee` command

### ISSUE THREAD

**Issue by KtorZ** [cardano-foundation/cardano-wallet#469]
# Context

https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/postTransactionFee

The implementation regarding the logic of this endpoint is already more-or-less available here:

https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/src/Cardano/Wallet.hs#L565-L581

Fees are the result of `sum outs - sum inps` which is easily computed after creating an unsigned transaction.

# Decision

Implement the `estimateFee` endpoint as outlined above. Since this is a small task, we'll also implement the command-line corresponding command. 

# Acceptance Criteria

1. `POST /api/v2/wallets/{walletId}/transactions/fees` _must_ return corresponding fee for a transaction. 
2. A `transaction fee` command in the CLI _must_ return corresponding fee for a transaction.
3. A root private key _mustn't_ be necessary to perform the operation in 1. and 2.
4. Both endpoint and command _should_ have the same API as their "real" duals (createTransaction), modulo the need for accessing a private key.

---

# Development Plan

- [x] I intend to add implementation to estimateFee endpoint and corresponding unit and integration tests
- [x] I intend to add cli support for fee estimation with corresponding tests

# PR

| Number   | Base      |
| ---      | ---       |
| #507       | `master`  |
| #516       | `master`  |
| #511       | `master`  |
| #533       | `master`  |
| #570       | `master`  |

# QA 

`estimateFee` endpoint was added together with API and CLI integration tests. It would be worth looking if all needed tests were added. Moreover, `validateSelection` was added to transaction layer with specific impl for each backends. The test were added to cover those boundary cases. It would be also worth trying this endpoint manually by sending curl REST request and via CLI

**Comment by piotr-iohk** [comment]
Looking good. (I've played around with API and CLI manually also) :+1: 

Two questions to `validateSelection` about `ErrExceededInpsOrOuts` in Jormungandr (https://github.com/input-output-hk/cardano-wallet/blob/master/lib/jormungandr/src/Cardano/Wallet/Jormungandr/Transaction.hs#L89):
1. As far as I understand, it is not likely to be reached since the max number of inputs or outputs should be always lower (cf: https://github.com/input-output-hk/cardano-wallet/pull/533#issuecomment-510884458) so it is just additional _guard_ not to post faulty transaction into jormungandr. Maybe there should be a comment in the code explaining this (somewhere here -> https://github.com/input-output-hk/cardano-wallet/blob/master/lib/jormungandr/src/Cardano/Wallet/Jormungandr/Transaction.hs#L89) ? 

2. Is it possible to add a `unit` test with 256 inputs/outputs and assert for the `TransactionIsTooBig` (https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/src/Cardano/Wallet/Api/Server.hs#L513) - if I understand correctly that would be the expected behavior now. Such test could be added on _integration_ level but it would take quite long time (~5 minutes) - not sure how it  could be added on _unit_ level. (cf https://github.com/input-output-hk/cardano-wallet/pull/533#issuecomment-510884458, https://github.com/input-output-hk/cardano-wallet/pull/533#issuecomment-510918979)

(@paweljakubas, @KtoZ)

**Comment by paweljakubas** [comment]
@piotr-iohk 

ad 1. So we have coin selection options https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/src/Cardano/Wallet/Primitive/CoinSelection.hs#L82 that has `maximumNumbeInputs` now working properly. Usually it is going to be lower than 256, and if so we will not catch `validateSelection` for Jormungandr. And in such a case, this functions as an additional guard. But, if this was not imposed, then we have explicit check, unique for each backend, that needs to be satisfied and also works as documentation.

ad 2. yes, we can add unit tests here

**Comment by piotr-iohk** [comment]
Unit test added in https://github.com/input-output-hk/cardano-wallet/pull/570.
