### ISSUE TITLE
Human readable address format of Jörmungandr has changed

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#630]
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Windows & OSX & Linux) | Code  v Configuration v Environment v Human v Unknown |

# Context

The user-facing encoding of Jörmungnadr addresses is bech32 which contains an human readable part (hrp) and a data part. Previously `jcli` used `ta` as hrp for the testnet network, and `ca` as hrp for the mainnet network.

Now 1) `jcli` uses `ca` when generating addresses regardless of network, 2) it provides a way for users to change hrp as they want, and 3) doesn't care which one is used when decoding

Relevant thread: https://input-output-rnd.slack.com/archives/CCPKJ93Q9/p1565775119035900
 
 

# Steps to Reproduce

1. Input addresses to the wallet via the CLI or API
2. Get the wallet to output addresses via the CLI or API
## Expected behavior

1. Wallet reads addresses with any Human Readable Part.
2. Wallet defaults to using `ca` as Human Readable Part, even on testnet, for output. 

Unconfirmed: Should the wallet remember the Human Readable Part for all addresses? Otherwise a user may input a `ta1s4...` address and get `ca1sw...` back.

## Actual behavior

Actual behaviour is unconfirmed, but likely wrong.
 
<A clear and concise description of what you observe instead. If applicable add screenshots to help explain your problem.>
---

# Resolution Plan

- Change the address prefix to be `addr` regardless of the network.

# PR

| Number   | Base      |
| ---      | ---       |
| #1000     | `master` |

# QA 

- Wallet backend now returns addresses prefixed with `addr`
- Swagger documentation also reflects this
- All tests still pass

**Comment by KtorZ** [comment]
@Anviking Thanks for opening this. 
Although Jörmungandr doesn't enforce any particular hrp for addresses anymore, I think we (as a user-facing app) still should. The node has a free format, precisely for allowing clients to choose one that is relevant for them. Since the encoding doesn't really interfere with the binary format, there's not much worry to have about addresses we would get from the node / network itself (unencoded). So, bech32 only occurs at the edge of our system: 

- The API
- The config file

and for those, I'd find it clearer to keep the visual discrimination in the hrp.  Though, that's a product decision to be confirmed.

**Comment by piotr-iohk** [comment]
Discussion: https://input-output-rnd.slack.com/archives/GBT05825V/p1571838723033200?thread_ts=1571837252.031500&cid=GBT05825V

**Comment by KtorZ** [comment]
So it appears that this is confusing quite a lot of people when playing with the explorer and the wallet. Being consistent with Jörmungandr and the explorer would help dispelling this confusion. Will do.

**Comment by piotr-iohk** [comment]
lgtm!
