### ISSUE TITLE
Calculate performance and list stake pools in the WalletLayer

### ISSUE THREAD

**Issue by Anviking** [cardano-foundation/cardano-wallet#714]
# Context

Clients should be able to list stake pools. 

We need a way to rank stake pools. For the incentivised testnet [we will](https://docs.google.com/document/d/1pjSa9KS9mvNXmPLZ2mHJJkKGooqvDFmg34CdATJPa38/edit#) use the formula
```
Approximate Performance = (n / N) * (S / s)
```
where
- `n` = number of blocks produced by the pool in the current epoch
- `N` = number of total blocks in the current epoch
- `s` = the stake of the pool in the current epoch
- `S` = the total delegated stake in the current epoch

It compares how many blocks a stake pool actually produces with how many it — on average — should produce given its stake. Because of the randomness the approximate performance will be less reliable with smaller amounts of data.

Unfortunately we _will_ have small amounts of data in the beginning of each epoch, since jörmungandr only provides the stake-distribution for the _current epoch_, which we might be in the beginning of.

Another problem is that we need to combine two different sources of data (the stake distribution from the REST api call, and the produced-blocks from our chain-state), which may get out of sync.

# Decision

Use the work from #711 and #713 to calculate the approximate performance of all stake pools in the current epoch. 

We'd like to have a `listStakePools`-function in the wallet layer.

It should end up something like this:
```haskell
listStakePools = do
	(epoch1, sortedList) <- getProducedBlocks db
	(epoch2, someList) <- getStakeDistribution nl
	-- epoch1 != epoch2 may be true for several reasons
```

If we are in the first 10% of the epoch, the performance should be unavailable.

# Acceptance Criteria

- [ ] The wallet layer _must_ implement a function `listStakePools` that return stake-pools with their id (public key),  approximate performance and stake.
- [ ] When in the first 10% of an epoch, the performance  _shoudn't_ be available.
- [ ] The result _should_ be sorted by approximate performance.
- [ ] `listStakePools` _should be_ as resistant to race-conditions as realistically possible

# Development Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #?       | `master`  |

# QA

**Comment by Anviking** [comment]
- It might be impossible to know if `getStakeDistribution` and `getProducedBlocks` are on the same chain. So we might have an undetectable race-condition which would make the calculated performance wrong.
- If we are going to sort the stake-pools after performance, and the performance can be unavailable… then that might be slightly awkward.

**Comment by KtorZ** [comment]
> **It might be impossible to know if getStakeDistribution and getProducedBlocks are on the same chain. So we might have an undetectable race-condition which would make the calculated performance wrong.**

It doesn't matter much here. We can only be off by `k` blocks, which is 10% of the whole epoch. Even if we are on a fork, we should still get a distribution that reflects rather correctly the state of the chain anyway (unless we are really on an adversarial node trying self-assigning blocks to itself which is probably safe to discard). 

> **If we are going to sort the stake-pools after performance, and the performance can be unavailable… then that might be slightly awkward.**

Indeed. But that's a best effort here :/ 


> ```hs
> listStakePools = do
>	(epoch1, sortedList) <- getProducedBlocks db
>	(epoch2, someList) <- getStakeDistribution nl
>	-- epoch1 != epoch2 may be true for several reasons

One way to solve some of the discrepancy and race-conditions between these two calls would be to make `epoch` an argument for both. During runtime, we know our current epoch, and we simply fetch data for this epoch. We might miss one block if we are really doing this on the edge of a slot, but this doesn't matter and doesn't male the result any more wrong.

**Comment by KtorZ** [comment]
From @rvl 

- I think if the wallet is not fully restored, then this function should not return a value.
- Is there any way to get the slot corresponding to the stake distribution? Then we could get pool production value for that slot and then the result will be consistent.
- Rather than returning no performance value at the start of the epoch, could the previous epoch's stake distibution be cached? Or is that out of scope?

**Comment by piotr-iohk** [comment]
> When in the first 10% of an epoch, the performance shoudn't be available.

If I understand correctly, If user doesn't have stake performance information for the first 10% of an epoch then he cannot list stake pools at that time and as a result he's unable to actually delegate (cause there's no sufficient information to make a decision about where to delegate).

If that's the case, then this sounds as a possible solution:

>Rather than returning no performance value at the start of the epoch, could the previous epoch's stake distibution be cached?

**Comment by KtorZ** [comment]
> If I understand correctly, If user doesn't have stake performance information for the first 10% of an epoch then he cannot list stake pools at that time and as a result he's unable to actually delegate (cause there's no sufficient information to make a decision about where to delegate).

I am afraid that your understanding is incorrect :grimacing:
 
I a user doesn't have stake performance information for the first 10%, then it can still list stake pools but, they'll could be reported with an estimated performance `unknown` or `in calculation`. User is still free to delegate regardless.

 > could the previous epoch's stake distibution be cached?

Not really no. The rationale is the following:

- At a given point in time, we only know the stake distribution of the current epoch (current in the sense of, the node's tip)
- We can't be sure that the wallet software will be up-and-running at every epoch. A user might turn his wallet on every month or every two weeks.

So, chances of _missing_ a distribution is quite likely. And, once we are at epoch `N`, we can't asked the node for `N-1`. In particular, if a user uninstall and re-install his wallet, then he looses all the "cached" information: there's no way to get it from the chain (we could if we were able to have a little control on how the node syncs, forcing it to make regular stops at each epoch for the wallet to query and synchronize the stake distribution of each epochs...).

---

Having said that: we could use a "best-effort" approach and persist any performance indicator we know of, encouraging users to turn on their wallet often-enough so that we can sync up about the data, and provide a metric that is averaged over all known epochs. 
This means that two wallets may actually report completely different metrics of a particular stake pool, depending on what information they have seen. Assuming a pool A performed well in epoch `N-1` and `N+1`, but was really bad in epoch `N` ... if a user didn't turn his wallet on during epoch `N`, then, the pool's performance will still look very good for him. 

We could also weight the average towards the most recent epoch, decreasing the value of old data over new ones. There are solutions though, I think what's described here is a good first take we can iterate upon if time allows it.

**Comment by Anviking** [comment]
> I think if the wallet is not fully restored, then this function should not return a value.
— @rvl 

That sounds sane to me.

> Is there any way to get the slot corresponding to the stake distribution? Then we could get pool production value for that slot and then the result will be consistent.
— @rvl 

The epoch number is included in the response. The slot number is not. So no, I believe.

> Rather than returning no performance value at the start of the epoch, could the previous epoch's stake distibution be cached? Or is that out of scope?
— @rvl 

I think @KtorZ makes good points for: no, let's keep that out of scope for now. 

I also note there is talk about being able to get stake-distributions from previous epochs from jörmungandr [here](https://docs.google.com/document/d/1pjSa9KS9mvNXmPLZ2mHJJkKGooqvDFmg34CdATJPa38/edit#).

> One way to solve some of the discrepancy and race-conditions between these two calls would be to make epoch an argument for both. During runtime, we know our current epoch, and we simply fetch data for this epoch. We might miss one block if we are really doing this on the edge of a slot, but this doesn't matter and doesn't male the result any more wrong.
— @KtorZ 

That might be on to something 🤔

**Comment by piotr-iohk** [comment]
>I a user doesn't have stake performance information for the first 10%, then it can still list stake pools but, they'll could be reported with an estimated performance unknown or in calculation. User is still free to delegate regardless.

I acknowledge that user is able to delegate then, but what I meant is that he does not have sufficient information to make a decision.

Looking at how it's going to look in Daedalus -> https://deploy-preview-1545--daedalus-storybook.netlify.com/?path=/story/staking--stake-pools#themeName=Cardano&localeName=English&osName=Windows. 

So does it mean that for the first 10% of the epoch, i.e. first 12h of the epoch (assuming it's 5 days) the list of stake pools won't have this color coding for their performance?

**Comment by KtorZ** [comment]
> So does it mean that for the first 10% of the epoch, i.e. first 12h of the epoch (assuming it's 5 days) the list of stake pools won't have this color coding for their performance?

Indeed. Unless we make a non-recoverable metric based on the past as described here (2nd part of the comment).

https://github.com/input-output-hk/cardano-wallet/issues/714#issuecomment-532291843

Users that are more active will be "rewarded" more (in the sense of, getting more data and better metrics).

**Comment by Anviking** [comment]
> Looking at how it's going to look in Daedalus -> https://deploy-preview-1545--daedalus-storybook.netlify.com/?path=/story/staking--stake-pools#themeName=Cardano&localeName=English&osName=Windows.

Ah! Thanks for sharing that.
